import { mkdirSync, writeFileSync } from 'node:fs';
import { commerceApi, groupedPlatform } from '@stackmap/core/samples';
import { layoutDiagram } from '../src/index';

const outDir = new URL('../../viewer/src/samples/', import.meta.url);
mkdirSync(outDir, { recursive: true });

const samples = { 'commerce-api': ['commerceApiLayout', commerceApi], 'grouped-platform': ['groupedPlatformLayout', groupedPlatform] } as const;

for (const [file, [exportName, draft]] of Object.entries(samples)) {
  const laidOut = await layoutDiagram(draft);
  const source = `// Generated by packages/layout/scripts/layout-samples.ts — do not edit.\nimport type { LaidOutDiagram } from '@stackmap/core';\n\nexport const ${exportName}: LaidOutDiagram = ${JSON.stringify(laidOut, null, 2)};\n`;
  writeFileSync(new URL(`${file}.layout.ts`, outDir), source);
  console.log(`wrote ${file}.layout.ts`);
}
