import { BRAND_SLUGS } from '@stackmap/core';
import { buildJsonSchema, HTTP_URL, ID_PATTERN, REPO_PATH, VISIBLE_TEXT } from './schema';

interface Node {
  type?: string;
  description?: string;
  properties?: Record<string, Node>;
  required?: string[];
  items?: Node;
  enum?: unknown[];
  pattern?: string;
  maxItems?: number;
  minItems?: number;
  maxLength?: number;
  exclusiveMinimum?: number;
  minimum?: number;
}

const PATTERNS: Record<string, string> = {
  [ID_PATTERN.source]: 'lowercase id: `a-z`, `0-9`, `-`, `_`; starts with a letter or digit',
  [VISIBLE_TEXT.source]: 'non-blank',
  [HTTP_URL.source]: 'http(s) URL',
  [REPO_PATH.source]: 'repo-relative path (no `..`, `\\`, `://` or leading `/`)',
};

const cell = (s: string) => s.replace(/\|/g, '\\|').replace(/\n/g, ' ');

function notes(n: Node, link?: string): string {
  const out: string[] = [];
  if (n.description) out.push(n.description.replace(/\.$/, ''));
  if (n.enum) out.push(`one of ${n.enum.map((v) => `\`${String(v)}\``).join(', ')}`);
  // Ids repeat everywhere; the pattern is stated once, in the intro.
  if (n.pattern && n.pattern !== ID_PATTERN.source) out.push(PATTERNS[n.pattern] ?? `matches \`${n.pattern}\``);
  if (n.pattern === ID_PATTERN.source && !n.description) out.push('id');
  if (n.maxLength !== undefined) out.push(`at most ${n.maxLength} characters`);
  if (n.minItems) out.push(`at least ${n.minItems}`);
  if (n.maxItems !== undefined) out.push(`at most ${n.maxItems}`);
  if (n.exclusiveMinimum !== undefined) out.push(`> ${n.exclusiveMinimum}`);
  else if (n.minimum !== undefined) out.push(`≥ ${n.minimum}`);
  if (n.type === 'array' && n.items?.pattern) out.push(`items: ${PATTERNS[n.items.pattern] ?? n.items.pattern}`);
  if (link) out.push(`see [${link}](#${link.replace(/[^a-z0-9]+/gi, '').toLowerCase()})`);
  return cell(out.join('. ') || '—');
}

const typeOf = (n: Node) => (n.enum ? 'enum' : n.type === 'integer' ? 'integer' : (n.type ?? 'any'));

export interface SchemaField {
  key: string;
  type: string;
  required: boolean;
  /** Markdown: inline code in backticks, links as [text](#anchor). */
  notes: string;
  /** the nested section this field's object or items are described in */
  link?: string;
}

export interface SchemaSection {
  name: string;
  description?: string;
  fields: SchemaField[];
}

/** The reference's sections in reading order, from the same JSON Schema `stackmap validate` enforces. */
export function schemaSections(): SchemaSection[] {
  const root = buildJsonSchema() as Node;
  const sections: SchemaSection[] = [];
  const visit = (name: string, obj: Node) => {
    const fields: SchemaField[] = [];
    const nested: [string, Node][] = [];
    for (const [key, prop] of Object.entries(obj.properties ?? {})) {
      const base = name === 'Diagram' ? key : `${name}.${key}`;
      let link: string | undefined;
      if (prop.type === 'object' && prop.properties) nested.push([(link = base), prop]);
      if (prop.type === 'array' && prop.items?.properties) nested.push([(link = `${base}[]`), prop.items]);
      fields.push({ key, type: typeOf(prop), required: obj.required?.includes(key) ?? false, notes: notes(prop, link), ...(link ? { link } : {}) });
    }
    sections.push({ name, ...(obj.description && name !== 'Diagram' ? { description: obj.description } : {}), fields });
    for (const [n, o] of nested) visit(n, o);
  };
  visit('Diagram', root);
  return sections;
}

/** Markdown reference for the skill, rendered from the same JSON Schema `stackmap validate` enforces. */
export function renderSchemaDoc(): string {
  const root = buildJsonSchema() as Node;
  const sections = schemaSections().map((s) =>
    [
      `## ${s.name}`,
      '',
      ...(s.description ? [s.description, ''] : []),
      '| Field | Type | Required | Notes |',
      '|---|---|---|---|',
      ...s.fields.map((f) => `| \`${f.key}\` | ${f.type} | ${f.required ? 'yes' : 'no'} | ${f.notes} |`),
    ].join('\n'),
  );
  return [
    '<!-- Generated by packages/schema/scripts/emit-schema.ts from the Zod schema. Do not edit. -->',
    '# stackmap diagram schema',
    '',
    `${root.description ?? ''} Machine-readable: [stackmap.schema.json](stackmap.schema.json). Objects are strict: unknown keys are errors. Ids (and references to them) use \`a-z\`, \`0-9\`, \`-\` and \`_\`, starting with a letter or digit.`,
    '',
    ...sections.flatMap((s) => [s, '']),
    '## Brand slugs',
    '',
    'Values allowed in `nodes[].card.brand` (Simple Icons, CC0). Anything else is a warning and the type icon is shown.',
    '',
    BRAND_SLUGS.map((b) => `\`${b}\``).join(' · '),
    '',
  ].join('\n');
}
