import { writeFileSync } from 'node:fs';
import { encodeKerning, type KerningPairs } from '../../core/src/font-metrics-codec';

type Tables = Record<string, Record<number, number>>;

/** Writes packages/core/src/font-metrics.gen.ts from measured advances and kerning (1/`unitsPerEm` em). */
export function writeFontMetrics(unitsPerEm: number, advances: Tables, kerning: Record<string, KerningPairs>): string {
  const faces = Object.keys(advances);
  const table = Object.entries(advances)
    .map(([name, m]) => `    ${name}: {${Object.entries(m).map(([k, v]) => `${k}:${v}`).join(',')}},`)
    .join('\n');
  const kern = Object.entries(encodeKerning(kerning))
    .map(([name, enc]) => `    ${name}: ${JSON.stringify(enc)},`)
    .join('\n');
  const file = new URL('../../core/src/font-metrics.gen.ts', import.meta.url);
  writeFileSync(
    file,
    `// Generated by packages/viewer/scripts/gen-font-metrics.ts — do not edit.\n` +
      `// Advance widths in 1/${unitsPerEm} em keyed by code point; kerning encoded by font-metrics-codec.ts.\n` +
      `import type { EncodedKerning } from './font-metrics-codec';\n\n` +
      `export type FontFace = ${faces.map((f) => `'${f}'`).join(' | ')};\n\n` +
      // Widened on purpose: literal types for thousands of keys make tsc slow and the tables unindexable.
      `export const FONT_METRICS: {\n  unitsPerEm: number;\n  faces: Record<FontFace, Record<number, number>>;\n  kerning: Record<FontFace, EncodedKerning<FontFace>>;\n} = {\n` +
      `  unitsPerEm: ${unitsPerEm},\n  faces: {\n${table}\n  },\n  kerning: {\n${kern}\n  },\n};\n`,
  );
  return file.pathname;
}
