// Generates src/icons/brands.gen.ts: title and path of each allowlisted simple-icons mark (core's
// BRAND_SLUGS). Each simple-icons export also carries its full SVG (the path again), colour and source
// URLs, which the viewer never uses: about half the icon bytes. Run: bun run icons:gen
import { writeFileSync } from 'node:fs';
import * as simpleIcons from 'simple-icons';
import { BRAND_SLUGS } from '../../core/src/brands';

const bySlug = new Map(Object.values(simpleIcons).map((i) => [i.slug, i]));
const entries = [...BRAND_SLUGS].sort().map((slug) => {
  const icon = bySlug.get(slug);
  if (!icon) throw new Error(`simple-icons has no "${slug}"`);
  return `  ${JSON.stringify(slug)}: { title: ${JSON.stringify(icon.title)}, path: ${JSON.stringify(icon.path)} },`;
});
writeFileSync(
  new URL('../src/icons/brands.gen.ts', import.meta.url),
  `// Generated by packages/viewer/scripts/gen-brand-icons.ts from simple-icons — do not edit.\n` +
    `export const BRANDS: Record<string, { title: string; path: string }> = {\n${entries.join('\n')}\n};\n`,
);
console.log(`wrote brands.gen.ts (${entries.length} marks)`);
