// Generates packages/core/src/font-metrics.gen.ts: per-glyph advances of the inlined Geist faces, measured
// by Chromium itself so weight-500 (a variable-font instance) and tabular digits match what users see.
// Run: bun run metrics:gen (needs `bunx playwright install chromium` once).
import { readFileSync, writeFileSync } from 'node:fs';
import { createRequire } from 'node:module';
import { chromium } from '@playwright/test';
import * as fontkit from 'fontkit';

const require = createRequire(import.meta.url);
const file = (spec: string) => readFileSync(require.resolve(spec));
const sans = file('@fontsource-variable/geist/files/geist-latin-wght-normal.woff2');
const mono = file('@fontsource-variable/geist-mono/files/geist-mono-latin-wght-normal.woff2');

// Only code points the subset actually covers; anything else renders in a fallback font.
const coverage = (buf: Buffer) =>
  (fontkit.create(buf) as fontkit.Font).characterSet.filter((cp) => cp >= 0x20).sort((a, b) => a - b);

const FACES = {
  sans400: { family: 'Geist', weight: 400, numeric: 'normal', cps: coverage(sans) },
  sans500: { family: 'Geist', weight: 500, numeric: 'normal', cps: coverage(sans) },
  sans500tnum: { family: 'Geist', weight: 500, numeric: 'tabular-nums', cps: coverage(sans) },
  mono400: { family: 'Geist Mono', weight: 400, numeric: 'normal', cps: coverage(mono) },
} as const;

const SIZE = 1000;
// Pairs are kept for printable ASCII only; negative pairs only when ≤ -5/1000 em (0.06px at 12px): the
// full table is ~0.5 MB. An omitted negative pair only makes the measure err wide.
const KERN_MIN = 5;
const browser = await chromium.launch();
const page = await browser.newPage();
const face = (family: string, buf: Buffer) =>
  `@font-face{font-family:'${family}';font-weight:100 900;src:url(data:font/woff2;base64,${buf.toString('base64')}) format('woff2')}`;
await page.setContent(`<style>${face('Geist', sans)}${face('Geist Mono', mono)}</style>`);
await page.evaluate(async () => {
  await Promise.all([
    document.fonts.load("400 16px 'Geist'"),
    document.fonts.load("500 16px 'Geist'"),
    document.fonts.load("400 16px 'Geist Mono'"),
  ]);
});

const out: Record<string, Record<number, number>> = {};
const kern: Record<string, Record<number, number>> = {};
for (const [name, f] of Object.entries(FACES)) {
  // Pair adjustment = kerned width of the pair minus both advances; only non-zero pairs are kept.
  kern[name] = await page.evaluate(
    ({ f, size, min }) => {
      const span = document.createElement('span');
      Object.assign(span.style, {
        fontFamily: `'${f.family}'`,
        fontWeight: String(f.weight),
        fontVariantNumeric: f.numeric,
        fontSize: `${size}px`,
        whiteSpace: 'pre',
        position: 'absolute',
      });
      document.body.append(span);
      const width = (t: string) => ((span.textContent = t), span.getBoundingClientRect().width);
      const adv = new Map(f.cps.map((cp) => [cp, width(String.fromCodePoint(cp))]));
      const pairs: Record<number, number> = {};
      const ascii = f.cps.filter((cp) => cp <= 0x7e);
      for (const a of ascii) {
        for (const b of ascii) {
          const k = Math.round((width(String.fromCodePoint(a, b)) - adv.get(a)! - adv.get(b)!) * 100) / 100;
          if (k >= 0.5 || k <= -min) pairs[a * 0x10000 + b] = k; // positive pairs always: dropping one under-measures
        }
      }
      span.remove();
      return pairs;
    },
    { f, size: SIZE, min: KERN_MIN },
  );
  out[name] = await page.evaluate(
    ({ f, size }) => {
      const span = document.createElement('span');
      Object.assign(span.style, {
        fontFamily: `'${f.family}'`,
        fontWeight: String(f.weight),
        fontVariantNumeric: f.numeric,
        fontSize: `${size}px`,
        whiteSpace: 'pre',
        position: 'absolute',
      });
      document.body.append(span);
      const adv: Record<number, number> = {};
      for (const cp of f.cps) {
        span.textContent = String.fromCodePoint(cp);
        adv[cp] = Math.round(span.getBoundingClientRect().width * 100) / 100;
      }
      span.remove();
      return adv;
    },
    { f, size: SIZE },
  );
}
await browser.close();

const table = (t: Record<string, Record<number, number>>) =>
  Object.entries(t)
    .map(([name, m]) => `    ${name}: {${Object.entries(m).map(([k, v]) => `${k}:${v}`).join(',')}},`)
    .join('\n');
writeFileSync(
  new URL('../../core/src/font-metrics.gen.ts', import.meta.url),
  `// Generated by packages/viewer/scripts/gen-font-metrics.ts — do not edit.\n` +
    `// Advance widths in 1/${SIZE} em keyed by code point; kerning keyed by first * 0x10000 + second.\n` +
    `export type FontFace = ${Object.keys(FACES).map((f) => `'${f}'`).join(' | ')};\n\n` +
    // Widened on purpose: literal types for ~12k keys make tsc slow and the tables unindexable.
    `type Table = Record<FontFace, Record<number, number>>;\n\n` +
    `export const FONT_METRICS: { unitsPerEm: number; faces: Table; kerning: Table } = {\n  unitsPerEm: ${SIZE},\n  faces: {\n${table(out)}\n  },\n  kerning: {\n${table(kern)}\n  },\n};\n`,
);
console.log(`wrote font-metrics.gen.ts (${Object.keys(out).map((n) => `${n}: ${Object.keys(out[n]!).length} glyphs, ${Object.keys(kern[n]!).length} pairs`).join('; ')})`);
