// Generated by packages/layout/scripts/layout-samples.ts — do not edit.
import type { LaidOutDiagram } from '@stackmap/core';

export const commerceApiLayout: LaidOutDiagram = {
  "draft": {
    "kind": "architecture",
    "title": "Commerce API",
    "subtitle": "Production topology",
    "source": {
      "url": "https://github.com/hyamero/stackmap/blob/main"
    },
    "direction": "RIGHT",
    "nodes": [
      {
        "id": "edge",
        "type": "gateway",
        "card": {
          "title": "OpenShip Edge",
          "subtitle": "Public routing",
          "rows": [
            {
              "label": "Load balancing",
              "value": "Round robin"
            }
          ],
          "footer": {
            "left": {
              "text": "EU West",
              "icon": "region"
            },
            "right": {
              "text": "HTTPS",
              "icon": "secure"
            }
          }
        }
      },
      {
        "id": "commerce-api-1",
        "type": "service",
        "card": {
          "title": "commerce-api-1",
          "subtitle": "API · Instance 1",
          "rows": [
            {
              "label": "2 vCPU · 2 GB",
              "value": ":3000",
              "mono": true
            }
          ],
          "footer": {
            "left": {
              "text": "EU West",
              "icon": "region"
            },
            "right": {
              "text": "Stateless"
            }
          }
        }
      },
      {
        "id": "commerce-api-2",
        "type": "service",
        "card": {
          "title": "commerce-api-2",
          "subtitle": "API · Instance 2",
          "rows": [
            {
              "label": "2 vCPU · 2 GB",
              "value": ":3000",
              "mono": true
            }
          ],
          "footer": {
            "left": {
              "text": "EU West",
              "icon": "region"
            },
            "right": {
              "text": "Stateless"
            }
          }
        }
      },
      {
        "id": "commerce-api-3",
        "type": "service",
        "card": {
          "title": "commerce-api-3",
          "subtitle": "API · Instance 3",
          "rows": [
            {
              "label": "2 vCPU · 2 GB",
              "value": ":3000",
              "mono": true
            }
          ],
          "footer": {
            "left": {
              "text": "EU West",
              "icon": "region"
            },
            "right": {
              "text": "Stateless"
            }
          }
        }
      },
      {
        "id": "orders",
        "evidence": [
          {
            "file": "infra/orders/postgres.tf",
            "line": 12,
            "note": "Primary + 2 read replicas"
          },
          {
            "file": "services/api/src/db.ts",
            "line": 8
          }
        ],
        "type": "database",
        "card": {
          "title": "Orders",
          "subtitle": "PostgreSQL cluster",
          "brand": "postgresql",
          "stats": [
            {
              "value": "1",
              "label": "Primary"
            },
            {
              "value": "2",
              "label": "Read replicas"
            }
          ],
          "statsNote": "2 replication links",
          "footer": {
            "left": {
              "text": "EU West",
              "icon": "region"
            },
            "right": {
              "text": "3 members",
              "icon": "members"
            }
          },
          "cta": {
            "label": "Open cluster",
            "href": "https://console.example.com/clusters/orders"
          }
        }
      },
      {
        "id": "sessions",
        "type": "cache",
        "card": {
          "title": "Sessions",
          "subtitle": "Redis cluster",
          "brand": "redis",
          "stats": [
            {
              "value": "3",
              "label": "Primary shards"
            },
            {
              "value": "3",
              "label": "Replicas"
            }
          ],
          "statsNote": "3 replication links",
          "footer": {
            "left": {
              "text": "EU West",
              "icon": "region"
            },
            "right": {
              "text": "6 members",
              "icon": "members"
            }
          },
          "cta": {
            "label": "Open cluster",
            "href": "https://console.example.com/clusters/sessions"
          }
        }
      }
    ],
    "edges": [
      {
        "id": "e-edge-1",
        "from": "edge",
        "to": "commerce-api-1"
      },
      {
        "id": "e-edge-2",
        "from": "edge",
        "to": "commerce-api-2"
      },
      {
        "id": "e-edge-3",
        "from": "edge",
        "to": "commerce-api-3"
      },
      {
        "id": "e-1-orders",
        "from": "commerce-api-1",
        "to": "orders"
      },
      {
        "id": "e-2-orders",
        "from": "commerce-api-2",
        "to": "orders"
      },
      {
        "id": "e-3-orders",
        "from": "commerce-api-3",
        "to": "orders"
      },
      {
        "id": "e-1-sessions",
        "from": "commerce-api-1",
        "to": "sessions"
      },
      {
        "id": "e-2-sessions",
        "from": "commerce-api-2",
        "to": "sessions"
      },
      {
        "id": "e-3-sessions",
        "from": "commerce-api-3",
        "to": "sessions"
      }
    ],
    "views": [
      {
        "id": "data",
        "label": "Data tier",
        "caption": "Where state lives",
        "nodes": [
          "orders",
          "sessions"
        ]
      }
    ]
  },
  "nodes": {
    "edge": {
      "x": 40,
      "y": 281,
      "width": 280,
      "height": 148
    },
    "commerce-api-1": {
      "x": 440,
      "y": 93,
      "width": 280,
      "height": 148
    },
    "commerce-api-2": {
      "x": 440,
      "y": 281,
      "width": 280,
      "height": 148
    },
    "commerce-api-3": {
      "x": 440,
      "y": 469,
      "width": 280,
      "height": 148
    },
    "orders": {
      "x": 840,
      "y": 40,
      "width": 280,
      "height": 254
    },
    "sessions": {
      "x": 840,
      "y": 334,
      "width": 280,
      "height": 254
    }
  },
  "groups": {},
  "edges": {
    "e-edge-1": [
      {
        "x": 320,
        "y": 355
      },
      {
        "x": 344,
        "y": 355
      },
      {
        "x": 344,
        "y": 167
      },
      {
        "x": 440,
        "y": 167
      }
    ],
    "e-edge-2": [
      {
        "x": 320,
        "y": 355
      },
      {
        "x": 440,
        "y": 355
      }
    ],
    "e-edge-3": [
      {
        "x": 320,
        "y": 355
      },
      {
        "x": 344,
        "y": 355
      },
      {
        "x": 344,
        "y": 543
      },
      {
        "x": 440,
        "y": 543
      }
    ],
    "e-1-orders": [
      {
        "x": 720,
        "y": 167
      },
      {
        "x": 840,
        "y": 167
      }
    ],
    "e-2-orders": [
      {
        "x": 720,
        "y": 355
      },
      {
        "x": 744,
        "y": 355
      },
      {
        "x": 744,
        "y": 167
      },
      {
        "x": 840,
        "y": 167
      }
    ],
    "e-3-orders": [
      {
        "x": 720,
        "y": 543
      },
      {
        "x": 744,
        "y": 543
      },
      {
        "x": 744,
        "y": 167
      },
      {
        "x": 840,
        "y": 167
      }
    ],
    "e-1-sessions": [
      {
        "x": 720,
        "y": 167
      },
      {
        "x": 744,
        "y": 167
      },
      {
        "x": 744,
        "y": 461
      },
      {
        "x": 840,
        "y": 461
      }
    ],
    "e-2-sessions": [
      {
        "x": 720,
        "y": 355
      },
      {
        "x": 744,
        "y": 355
      },
      {
        "x": 744,
        "y": 461
      },
      {
        "x": 840,
        "y": 461
      }
    ],
    "e-3-sessions": [
      {
        "x": 720,
        "y": 543
      },
      {
        "x": 744,
        "y": 543
      },
      {
        "x": 744,
        "y": 461
      },
      {
        "x": 840,
        "y": 461
      }
    ]
  },
  "bounds": {
    "width": 1160,
    "height": 657
  },
  "labels": {}
};
