// Generated by packages/layout/scripts/layout-samples.ts — do not edit.
import type { LaidOutDiagram } from '@stackmap/core';

export const galleryLayouts: Record<string, LaidOutDiagram> = {
  "release-delivery": {
    "draft": {
      "kind": "workflow",
      "title": "Release delivery",
      "subtitle": "From commit to announced release",
      "lanes": [
        {
          "id": "dev",
          "label": "Developer"
        },
        {
          "id": "ci",
          "label": "Continuous integration"
        },
        {
          "id": "approval",
          "label": "Release governance"
        },
        {
          "id": "environment",
          "label": "Production environment"
        },
        {
          "id": "communication",
          "label": "Release communication"
        },
        {
          "id": "exceptions",
          "label": "Failure and rollback",
          "tone": "exception"
        }
      ],
      "phases": [
        {
          "id": "change",
          "label": "Change",
          "nodes": [
            "commit",
            "pull-request"
          ]
        },
        {
          "id": "verify",
          "label": "Build and verify",
          "nodes": [
            "build",
            "checks",
            "failed"
          ]
        },
        {
          "id": "promote",
          "label": "Promote and observe",
          "nodes": [
            "approve",
            "deploy",
            "verify-prod",
            "announce",
            "rollback"
          ]
        }
      ],
      "groups": [
        {
          "id": "blocking-checks",
          "label": "Blocking checks"
        },
        {
          "id": "recovery",
          "label": "Recovery path",
          "tone": "security"
        }
      ],
      "nodes": [
        {
          "id": "commit",
          "type": "client",
          "lane": "dev",
          "card": {
            "title": "Commit",
            "subtitle": "Signed change"
          }
        },
        {
          "id": "pull-request",
          "type": "client",
          "lane": "dev",
          "card": {
            "title": "Pull request",
            "subtitle": "Reviewed diff"
          }
        },
        {
          "id": "build",
          "type": "service",
          "lane": "ci",
          "group": "blocking-checks",
          "card": {
            "title": "Build",
            "subtitle": "Locked inputs",
            "tag": "reproducible",
            "brand": "githubactions"
          }
        },
        {
          "id": "checks",
          "type": "security",
          "lane": "ci",
          "group": "blocking-checks",
          "card": {
            "title": "Quality gates",
            "subtitle": "Test and scan",
            "tag": "blocking"
          }
        },
        {
          "id": "approve",
          "type": "security",
          "lane": "approval",
          "card": {
            "title": "Approve",
            "subtitle": "Release owner",
            "tag": "human gate"
          }
        },
        {
          "id": "deploy",
          "type": "gateway",
          "lane": "environment",
          "card": {
            "title": "Deploy",
            "subtitle": "Canary 10%",
            "tag": "production",
            "brand": "kubernetes"
          }
        },
        {
          "id": "verify-prod",
          "type": "service",
          "lane": "environment",
          "card": {
            "title": "Verify",
            "subtitle": "Smoke and SLO"
          }
        },
        {
          "id": "announce",
          "type": "external",
          "lane": "communication",
          "card": {
            "title": "Announce",
            "subtitle": "Status and notes"
          }
        },
        {
          "id": "failed",
          "type": "security",
          "lane": "exceptions",
          "card": {
            "title": "Stop release",
            "subtitle": "Gate failed"
          }
        },
        {
          "id": "rollback",
          "type": "queue",
          "lane": "exceptions",
          "group": "recovery",
          "card": {
            "title": "Rollback",
            "subtitle": "Last good image",
            "tag": "owner: on-call"
          }
        }
      ],
      "edges": [
        {
          "id": "e1",
          "from": "commit",
          "to": "pull-request",
          "tone": "main"
        },
        {
          "id": "e2",
          "from": "pull-request",
          "to": "build",
          "label": "merge",
          "tone": "main"
        },
        {
          "id": "e3",
          "from": "build",
          "to": "checks",
          "tone": "main"
        },
        {
          "id": "e4",
          "from": "checks",
          "to": "approve",
          "tone": "main"
        },
        {
          "id": "e5",
          "from": "approve",
          "to": "deploy",
          "tone": "main"
        },
        {
          "id": "e6",
          "from": "deploy",
          "to": "verify-prod",
          "tone": "main"
        },
        {
          "id": "e7",
          "from": "verify-prod",
          "to": "announce",
          "label": "healthy",
          "tone": "main"
        },
        {
          "id": "e8",
          "from": "checks",
          "to": "failed",
          "label": "red",
          "tone": "error"
        },
        {
          "id": "e9",
          "from": "verify-prod",
          "to": "rollback",
          "label": "unhealthy",
          "tone": "error"
        },
        {
          "id": "e10",
          "from": "rollback",
          "to": "deploy",
          "label": "restore",
          "kind": "return"
        }
      ],
      "views": [
        {
          "id": "happy",
          "label": "Happy path",
          "caption": "Every change is reviewed, built once and verified in production before it is announced.",
          "nodes": [
            "commit",
            "pull-request",
            "build",
            "checks",
            "approve",
            "deploy",
            "verify-prod",
            "announce"
          ]
        },
        {
          "id": "stops",
          "label": "Stop conditions",
          "caption": "A red gate stops promotion; an unhealthy release rolls back to the last good image.",
          "nodes": [
            "checks",
            "failed",
            "verify-prod",
            "rollback",
            "deploy"
          ]
        }
      ],
      "notes": [
        {
          "title": "One happy path",
          "items": [
            "Every change is reviewed before a reproducible build",
            "Blocking checks must be green before human approval",
            "Production is complete only after smoke and SLO verification"
          ]
        },
        {
          "title": "Stop conditions",
          "items": [
            "Test or security failure stops promotion",
            "Production health can reverse a release",
            "Rollback ownership is visible before an incident"
          ]
        }
      ]
    },
    "nodes": {
      "commit": {
        "x": 184,
        "y": 108,
        "width": 176,
        "height": 60
      },
      "pull-request": {
        "x": 424,
        "y": 108,
        "width": 176,
        "height": 60
      },
      "build": {
        "x": 664,
        "y": 272,
        "width": 176,
        "height": 84
      },
      "checks": {
        "x": 904,
        "y": 272,
        "width": 176,
        "height": 84
      },
      "approve": {
        "x": 1144,
        "y": 432,
        "width": 176,
        "height": 84
      },
      "deploy": {
        "x": 1144,
        "y": 580,
        "width": 176,
        "height": 84
      },
      "verify-prod": {
        "x": 1384,
        "y": 592,
        "width": 176,
        "height": 60
      },
      "announce": {
        "x": 1384,
        "y": 728,
        "width": 176,
        "height": 60
      },
      "failed": {
        "x": 904,
        "y": 904,
        "width": 176,
        "height": 60
      },
      "rollback": {
        "x": 1384,
        "y": 892,
        "width": 176,
        "height": 84
      }
    },
    "groups": {
      "blocking-checks": {
        "x": 652,
        "y": 232,
        "width": 440,
        "height": 136
      },
      "recovery": {
        "x": 1372,
        "y": 852,
        "width": 200,
        "height": 136
      }
    },
    "edges": {
      "e1": [
        {
          "x": 360,
          "y": 138
        },
        {
          "x": 424,
          "y": 138
        }
      ],
      "e2": [
        {
          "x": 568,
          "y": 168
        },
        {
          "x": 568,
          "y": 314
        },
        {
          "x": 664,
          "y": 314
        }
      ],
      "e3": [
        {
          "x": 840,
          "y": 314
        },
        {
          "x": 904,
          "y": 314
        }
      ],
      "e4": [
        {
          "x": 1080,
          "y": 314
        },
        {
          "x": 1176,
          "y": 314
        },
        {
          "x": 1176,
          "y": 432
        }
      ],
      "e5": [
        {
          "x": 1232,
          "y": 516
        },
        {
          "x": 1232,
          "y": 580
        }
      ],
      "e6": [
        {
          "x": 1320,
          "y": 622
        },
        {
          "x": 1384,
          "y": 622
        }
      ],
      "e7": [
        {
          "x": 1472,
          "y": 652
        },
        {
          "x": 1472,
          "y": 728
        }
      ],
      "e8": [
        {
          "x": 992,
          "y": 356
        },
        {
          "x": 992,
          "y": 904
        }
      ],
      "e9": [
        {
          "x": 1528,
          "y": 652
        },
        {
          "x": 1528,
          "y": 708
        },
        {
          "x": 1576,
          "y": 708
        },
        {
          "x": 1576,
          "y": 872
        },
        {
          "x": 1528,
          "y": 872
        },
        {
          "x": 1528,
          "y": 892
        }
      ],
      "e10": [
        {
          "x": 1384,
          "y": 934
        },
        {
          "x": 1288,
          "y": 934
        },
        {
          "x": 1288,
          "y": 664
        }
      ]
    },
    "lanes": {
      "dev": {
        "x": 40,
        "y": 88,
        "width": 1552,
        "height": 108
      },
      "ci": {
        "x": 40,
        "y": 212,
        "width": 1552,
        "height": 184
      },
      "approval": {
        "x": 40,
        "y": 412,
        "width": 1552,
        "height": 132
      },
      "environment": {
        "x": 40,
        "y": 560,
        "width": 1552,
        "height": 132
      },
      "communication": {
        "x": 40,
        "y": 708,
        "width": 1552,
        "height": 108
      },
      "exceptions": {
        "x": 40,
        "y": 832,
        "width": 1552,
        "height": 184
      }
    },
    "phases": {
      "change": {
        "x": 160,
        "y": 40,
        "width": 464,
        "height": 40
      },
      "verify": {
        "x": 640,
        "y": 40,
        "width": 464,
        "height": 40
      },
      "promote": {
        "x": 1120,
        "y": 40,
        "width": 464,
        "height": 40
      }
    },
    "labels": {
      "e2": {
        "x": 616,
        "y": 314
      },
      "e7": {
        "x": 1472,
        "y": 690
      },
      "e8": {
        "x": 992,
        "y": 630
      },
      "e9": {
        "x": 1576,
        "y": 814.6
      },
      "e10": {
        "x": 1288,
        "y": 799
      }
    },
    "bounds": {
      "width": 1632,
      "height": 1056
    }
  },
  "incident-response": {
    "draft": {
      "kind": "workflow",
      "title": "Incident response runbook",
      "subtitle": "Detect, command, mitigate, verify",
      "lanes": [
        {
          "id": "signals",
          "label": "Signals"
        },
        {
          "id": "command",
          "label": "Incident command"
        },
        {
          "id": "mitigation",
          "label": "Service mitigation"
        },
        {
          "id": "recovery",
          "label": "Recovery evidence"
        },
        {
          "id": "communication",
          "label": "Stakeholder communication"
        },
        {
          "id": "exceptions",
          "label": "Escalation and rollback",
          "tone": "exception"
        }
      ],
      "phases": [
        {
          "id": "detect",
          "label": "Detect",
          "nodes": [
            "alert",
            "page"
          ]
        },
        {
          "id": "triage",
          "label": "Triage and mitigate",
          "nodes": [
            "triage",
            "declare",
            "contain",
            "update",
            "escalate"
          ]
        },
        {
          "id": "close",
          "label": "Verify and close",
          "nodes": [
            "recover",
            "verify",
            "resolve",
            "rollback"
          ]
        }
      ],
      "groups": [
        {
          "id": "owners",
          "label": "Command owns the incident"
        }
      ],
      "nodes": [
        {
          "id": "alert",
          "type": "queue",
          "lane": "signals",
          "card": {
            "title": "SLO alert",
            "subtitle": "Burn rate",
            "brand": "pagerduty"
          }
        },
        {
          "id": "page",
          "type": "external",
          "lane": "command",
          "group": "owners",
          "card": {
            "title": "Page on-call",
            "subtitle": "Acknowledge"
          }
        },
        {
          "id": "triage",
          "type": "service",
          "lane": "command",
          "group": "owners",
          "card": {
            "title": "Triage",
            "subtitle": "Scope impact"
          }
        },
        {
          "id": "declare",
          "type": "security",
          "lane": "command",
          "group": "owners",
          "card": {
            "title": "Declare",
            "subtitle": "Assign commander",
            "tag": "SEV-1/2"
          }
        },
        {
          "id": "contain",
          "type": "service",
          "lane": "mitigation",
          "card": {
            "title": "Contain",
            "subtitle": "Stop growth"
          }
        },
        {
          "id": "recover",
          "type": "gateway",
          "lane": "mitigation",
          "card": {
            "title": "Recover",
            "subtitle": "Restore service"
          }
        },
        {
          "id": "verify",
          "type": "database",
          "lane": "recovery",
          "card": {
            "title": "Verify",
            "subtitle": "SLO and traces",
            "tag": "15 min stable"
          }
        },
        {
          "id": "update",
          "type": "client",
          "lane": "communication",
          "card": {
            "title": "Status update",
            "subtitle": "Impact and ETA"
          }
        },
        {
          "id": "resolve",
          "type": "external",
          "lane": "communication",
          "card": {
            "title": "Resolve",
            "subtitle": "Final update"
          }
        },
        {
          "id": "escalate",
          "type": "security",
          "lane": "exceptions",
          "card": {
            "title": "Escalate",
            "subtitle": "Specialist"
          }
        },
        {
          "id": "rollback",
          "type": "queue",
          "lane": "exceptions",
          "card": {
            "title": "Rollback",
            "subtitle": "Last good"
          }
        }
      ],
      "edges": [
        {
          "id": "e1",
          "from": "alert",
          "to": "page",
          "label": "page",
          "tone": "main"
        },
        {
          "id": "e2",
          "from": "page",
          "to": "triage",
          "tone": "main"
        },
        {
          "id": "e3",
          "from": "triage",
          "to": "contain",
          "tone": "main"
        },
        {
          "id": "e4",
          "from": "contain",
          "to": "recover",
          "tone": "main"
        },
        {
          "id": "e5",
          "from": "recover",
          "to": "verify",
          "tone": "main"
        },
        {
          "id": "e6",
          "from": "verify",
          "to": "resolve",
          "tone": "main"
        },
        {
          "id": "e7",
          "from": "triage",
          "to": "declare",
          "tone": "security"
        },
        {
          "id": "e8",
          "from": "declare",
          "to": "update",
          "kind": "async"
        },
        {
          "id": "e9",
          "from": "update",
          "to": "escalate",
          "label": "still impacted",
          "tone": "security"
        },
        {
          "id": "e10",
          "from": "verify",
          "to": "rollback",
          "label": "regressed",
          "tone": "error"
        }
      ],
      "views": [
        {
          "id": "command",
          "label": "Command",
          "caption": "A page is not an incident until someone owns command.",
          "nodes": [
            "alert",
            "page",
            "triage",
            "declare",
            "update"
          ]
        },
        {
          "id": "recovery",
          "label": "Recovery",
          "caption": "Mitigation reduces impact; only a stable SLO window proves recovery.",
          "nodes": [
            "contain",
            "recover",
            "verify",
            "resolve",
            "rollback"
          ]
        }
      ],
      "notes": [
        {
          "title": "Ownership first",
          "items": [
            "A page is not an incident until someone owns command",
            "Severity and scope are explicit before mitigation spreads",
            "Escalation names the missing expertise"
          ]
        },
        {
          "title": "Recovery is evidence",
          "items": [
            "Mitigation can reduce impact without proving recovery",
            "SLOs and traces must stay healthy for a fixed window",
            "The final update follows verification, not optimism"
          ]
        }
      ]
    },
    "nodes": {
      "alert": {
        "x": 184,
        "y": 108,
        "width": 176,
        "height": 60
      },
      "page": {
        "x": 184,
        "y": 284,
        "width": 176,
        "height": 60
      },
      "triage": {
        "x": 424,
        "y": 284,
        "width": 176,
        "height": 60
      },
      "declare": {
        "x": 664,
        "y": 272,
        "width": 176,
        "height": 84
      },
      "contain": {
        "x": 424,
        "y": 432,
        "width": 176,
        "height": 60
      },
      "recover": {
        "x": 904,
        "y": 432,
        "width": 176,
        "height": 60
      },
      "verify": {
        "x": 904,
        "y": 556,
        "width": 176,
        "height": 84
      },
      "update": {
        "x": 664,
        "y": 704,
        "width": 176,
        "height": 60
      },
      "resolve": {
        "x": 904,
        "y": 704,
        "width": 176,
        "height": 60
      },
      "escalate": {
        "x": 664,
        "y": 828,
        "width": 176,
        "height": 60
      },
      "rollback": {
        "x": 904,
        "y": 828,
        "width": 176,
        "height": 60
      }
    },
    "groups": {
      "owners": {
        "x": 172,
        "y": 232,
        "width": 680,
        "height": 136
      }
    },
    "edges": {
      "e1": [
        {
          "x": 216,
          "y": 168
        },
        {
          "x": 216,
          "y": 204
        },
        {
          "x": 168,
          "y": 204
        },
        {
          "x": 168,
          "y": 264
        },
        {
          "x": 216,
          "y": 264
        },
        {
          "x": 216,
          "y": 284
        }
      ],
      "e2": [
        {
          "x": 360,
          "y": 314
        },
        {
          "x": 424,
          "y": 314
        }
      ],
      "e3": [
        {
          "x": 512,
          "y": 344
        },
        {
          "x": 512,
          "y": 432
        }
      ],
      "e4": [
        {
          "x": 600,
          "y": 462
        },
        {
          "x": 904,
          "y": 462
        }
      ],
      "e5": [
        {
          "x": 992,
          "y": 492
        },
        {
          "x": 992,
          "y": 556
        }
      ],
      "e6": [
        {
          "x": 992,
          "y": 640
        },
        {
          "x": 992,
          "y": 704
        }
      ],
      "e7": [
        {
          "x": 600,
          "y": 314
        },
        {
          "x": 664,
          "y": 314
        }
      ],
      "e8": [
        {
          "x": 752,
          "y": 356
        },
        {
          "x": 752,
          "y": 704
        }
      ],
      "e9": [
        {
          "x": 752,
          "y": 764
        },
        {
          "x": 752,
          "y": 828
        }
      ],
      "e10": [
        {
          "x": 1048,
          "y": 640
        },
        {
          "x": 1048,
          "y": 684
        },
        {
          "x": 1096,
          "y": 684
        },
        {
          "x": 1096,
          "y": 808
        },
        {
          "x": 1048,
          "y": 808
        },
        {
          "x": 1048,
          "y": 828
        }
      ]
    },
    "lanes": {
      "signals": {
        "x": 40,
        "y": 88,
        "width": 1072,
        "height": 108
      },
      "command": {
        "x": 40,
        "y": 212,
        "width": 1072,
        "height": 184
      },
      "mitigation": {
        "x": 40,
        "y": 412,
        "width": 1072,
        "height": 108
      },
      "recovery": {
        "x": 40,
        "y": 536,
        "width": 1072,
        "height": 132
      },
      "communication": {
        "x": 40,
        "y": 684,
        "width": 1072,
        "height": 108
      },
      "exceptions": {
        "x": 40,
        "y": 808,
        "width": 1072,
        "height": 108
      }
    },
    "phases": {
      "detect": {
        "x": 160,
        "y": 40,
        "width": 224,
        "height": 40
      },
      "triage": {
        "x": 400,
        "y": 40,
        "width": 464,
        "height": 40
      },
      "close": {
        "x": 880,
        "y": 40,
        "width": 224,
        "height": 40
      }
    },
    "labels": {
      "e1": {
        "x": 168,
        "y": 234
      },
      "e9": {
        "x": 752,
        "y": 796
      },
      "e10": {
        "x": 1096,
        "y": 783.2
      }
    },
    "bounds": {
      "width": 1152,
      "height": 956
    }
  },
  "agent-tool-call": {
    "draft": {
      "kind": "workflow",
      "title": "Agent tool call",
      "subtitle": "Request, plan, approve, execute, reply",
      "lanes": [
        {
          "id": "ui",
          "label": "User interface"
        },
        {
          "id": "agent",
          "label": "Agent runtime"
        },
        {
          "id": "policy",
          "label": "Policy and recovery",
          "tone": "exception"
        },
        {
          "id": "tools",
          "label": "Tool execution and evidence"
        }
      ],
      "phases": [
        {
          "id": "intake",
          "label": "Intake",
          "nodes": [
            "user",
            "chat",
            "store"
          ]
        },
        {
          "id": "plan",
          "label": "Plan and route",
          "nodes": [
            "planner",
            "router",
            "approval"
          ]
        },
        {
          "id": "execute",
          "label": "Execute and report",
          "nodes": [
            "tool",
            "external",
            "blocked",
            "retry",
            "final"
          ]
        }
      ],
      "groups": [
        {
          "id": "loop",
          "label": "Planning loop"
        },
        {
          "id": "stop",
          "label": "Human or policy stop",
          "tone": "security"
        }
      ],
      "nodes": [
        {
          "id": "user",
          "type": "external",
          "lane": "ui",
          "card": {
            "title": "User",
            "subtitle": "Asks for work"
          }
        },
        {
          "id": "chat",
          "type": "client",
          "lane": "ui",
          "card": {
            "title": "Chat surface",
            "subtitle": "Thread and files"
          }
        },
        {
          "id": "final",
          "type": "service",
          "lane": "ui",
          "card": {
            "title": "Final reply",
            "subtitle": "Answer and changes"
          }
        },
        {
          "id": "planner",
          "type": "service",
          "lane": "agent",
          "group": "loop",
          "card": {
            "title": "Agent planner",
            "subtitle": "Plan next step",
            "tag": "context aware",
            "brand": "anthropic"
          }
        },
        {
          "id": "router",
          "type": "service",
          "lane": "agent",
          "group": "loop",
          "card": {
            "title": "Tool router",
            "subtitle": "Choose capability"
          }
        },
        {
          "id": "approval",
          "type": "security",
          "lane": "policy",
          "group": "stop",
          "card": {
            "title": "Approval gate",
            "subtitle": "Scope and consent",
            "tag": "blocks risky ops"
          }
        },
        {
          "id": "blocked",
          "type": "security",
          "lane": "policy",
          "group": "stop",
          "card": {
            "title": "Blocked",
            "subtitle": "Wait or reject"
          }
        },
        {
          "id": "retry",
          "type": "queue",
          "lane": "policy",
          "group": "stop",
          "card": {
            "title": "Retry path",
            "subtitle": "Revise request"
          }
        },
        {
          "id": "tool",
          "type": "queue",
          "lane": "tools",
          "card": {
            "title": "Tool call",
            "subtitle": "Shell, browser, MCP",
            "tag": "structured result"
          }
        },
        {
          "id": "external",
          "type": "gateway",
          "lane": "tools",
          "card": {
            "title": "External API",
            "subtitle": "Network service"
          }
        },
        {
          "id": "store",
          "type": "database",
          "lane": "tools",
          "card": {
            "title": "Context store",
            "subtitle": "Repo and memory"
          }
        },
        {
          "id": "trace",
          "type": "database",
          "lane": "tools",
          "card": {
            "title": "Trace log",
            "subtitle": "Events and output"
          }
        }
      ],
      "edges": [
        {
          "id": "e1",
          "from": "user",
          "to": "chat",
          "tone": "main"
        },
        {
          "id": "e2",
          "from": "chat",
          "to": "planner",
          "label": "plan",
          "tone": "main"
        },
        {
          "id": "e3",
          "from": "planner",
          "to": "router",
          "tone": "main"
        },
        {
          "id": "e4",
          "from": "router",
          "to": "approval",
          "label": "needs approval?",
          "tone": "security"
        },
        {
          "id": "e5",
          "from": "approval",
          "to": "tool",
          "label": "approved",
          "tone": "main"
        },
        {
          "id": "e6",
          "from": "approval",
          "to": "blocked",
          "label": "denied",
          "tone": "error"
        },
        {
          "id": "e7",
          "from": "blocked",
          "to": "retry",
          "kind": "async"
        },
        {
          "id": "e8",
          "from": "retry",
          "to": "planner",
          "label": "revise",
          "kind": "return"
        },
        {
          "id": "e9",
          "from": "tool",
          "to": "external",
          "tone": "main"
        },
        {
          "id": "e10",
          "from": "external",
          "to": "final",
          "label": "result",
          "kind": "return",
          "tone": "main"
        },
        {
          "id": "e11",
          "from": "external",
          "to": "trace",
          "label": "record",
          "kind": "async"
        },
        {
          "id": "e12",
          "from": "store",
          "to": "trace",
          "kind": "async"
        },
        {
          "id": "e13",
          "from": "store",
          "to": "planner",
          "label": "context",
          "kind": "async"
        }
      ],
      "views": [
        {
          "id": "gate",
          "label": "Approval gate",
          "caption": "Risky work waits for scope and consent before any tool runs.",
          "nodes": [
            "router",
            "approval",
            "tool",
            "blocked",
            "retry"
          ]
        }
      ],
      "notes": [
        {
          "title": "Runtime semantics",
          "items": [
            "Approval gates risky work before tool execution",
            "A denial loops back to planning instead of failing silently",
            "Evidence returns through the trace log and memory"
          ]
        }
      ]
    },
    "nodes": {
      "user": {
        "x": 184,
        "y": 108,
        "width": 176,
        "height": 60
      },
      "chat": {
        "x": 436,
        "y": 108,
        "width": 176,
        "height": 60
      },
      "final": {
        "x": 1192,
        "y": 108,
        "width": 176,
        "height": 60
      },
      "planner": {
        "x": 688,
        "y": 272,
        "width": 176,
        "height": 84
      },
      "router": {
        "x": 940,
        "y": 284,
        "width": 176,
        "height": 60
      },
      "approval": {
        "x": 940,
        "y": 472,
        "width": 176,
        "height": 84
      },
      "blocked": {
        "x": 1192,
        "y": 484,
        "width": 176,
        "height": 60
      },
      "retry": {
        "x": 1444,
        "y": 484,
        "width": 176,
        "height": 60
      },
      "tool": {
        "x": 1192,
        "y": 632,
        "width": 176,
        "height": 84
      },
      "external": {
        "x": 1444,
        "y": 644,
        "width": 176,
        "height": 60
      },
      "store": {
        "x": 184,
        "y": 644,
        "width": 176,
        "height": 60
      },
      "trace": {
        "x": 1696,
        "y": 644,
        "width": 176,
        "height": 60
      }
    },
    "groups": {
      "loop": {
        "x": 676,
        "y": 232,
        "width": 452,
        "height": 136
      },
      "stop": {
        "x": 928,
        "y": 432,
        "width": 704,
        "height": 136
      }
    },
    "edges": {
      "e1": [
        {
          "x": 360,
          "y": 138
        },
        {
          "x": 436,
          "y": 138
        }
      ],
      "e2": [
        {
          "x": 580,
          "y": 168
        },
        {
          "x": 580,
          "y": 314
        },
        {
          "x": 688,
          "y": 314
        }
      ],
      "e3": [
        {
          "x": 864,
          "y": 314
        },
        {
          "x": 940,
          "y": 314
        }
      ],
      "e4": [
        {
          "x": 1084,
          "y": 344
        },
        {
          "x": 1084,
          "y": 472
        }
      ],
      "e5": [
        {
          "x": 1084,
          "y": 556
        },
        {
          "x": 1084,
          "y": 674
        },
        {
          "x": 1192,
          "y": 674
        }
      ],
      "e6": [
        {
          "x": 1116,
          "y": 514
        },
        {
          "x": 1192,
          "y": 514
        }
      ],
      "e7": [
        {
          "x": 1368,
          "y": 514
        },
        {
          "x": 1444,
          "y": 514
        }
      ],
      "e8": [
        {
          "x": 1476,
          "y": 484
        },
        {
          "x": 1476,
          "y": 376
        },
        {
          "x": 832,
          "y": 376
        },
        {
          "x": 832,
          "y": 356
        }
      ],
      "e9": [
        {
          "x": 1368,
          "y": 674
        },
        {
          "x": 1444,
          "y": 674
        }
      ],
      "e10": [
        {
          "x": 1444,
          "y": 662
        },
        {
          "x": 1388,
          "y": 662
        },
        {
          "x": 1388,
          "y": 138
        },
        {
          "x": 1368,
          "y": 138
        }
      ],
      "e11": [
        {
          "x": 1620,
          "y": 674
        },
        {
          "x": 1696,
          "y": 674
        }
      ],
      "e12": [
        {
          "x": 360,
          "y": 674
        },
        {
          "x": 1056,
          "y": 674
        },
        {
          "x": 1056,
          "y": 730
        },
        {
          "x": 1676,
          "y": 730
        },
        {
          "x": 1676,
          "y": 674
        },
        {
          "x": 1696,
          "y": 674
        }
      ],
      "e13": [
        {
          "x": 360,
          "y": 674
        },
        {
          "x": 720,
          "y": 674
        },
        {
          "x": 720,
          "y": 356
        }
      ]
    },
    "lanes": {
      "ui": {
        "x": 40,
        "y": 88,
        "width": 1864,
        "height": 108
      },
      "agent": {
        "x": 40,
        "y": 212,
        "width": 1864,
        "height": 184
      },
      "policy": {
        "x": 40,
        "y": 412,
        "width": 1864,
        "height": 184
      },
      "tools": {
        "x": 40,
        "y": 612,
        "width": 1864,
        "height": 132
      }
    },
    "phases": {
      "intake": {
        "x": 154,
        "y": 40,
        "width": 488,
        "height": 40
      },
      "plan": {
        "x": 658,
        "y": 40,
        "width": 488,
        "height": 40
      },
      "execute": {
        "x": 1162,
        "y": 40,
        "width": 488,
        "height": 40
      }
    },
    "labels": {
      "e2": {
        "x": 634,
        "y": 314
      },
      "e4": {
        "x": 1084,
        "y": 408
      },
      "e5": {
        "x": 1138,
        "y": 674
      },
      "e6": {
        "x": 1154,
        "y": 514
      },
      "e8": {
        "x": 1154,
        "y": 376
      },
      "e10": {
        "x": 1388,
        "y": 400
      },
      "e11": {
        "x": 1658,
        "y": 674
      },
      "e13": {
        "x": 540,
        "y": 674
      }
    },
    "bounds": {
      "width": 1944,
      "height": 784
    }
  },
  "agent-run": {
    "draft": {
      "kind": "lifecycle",
      "title": "Agent run lifecycle",
      "subtitle": "States of one agent run",
      "lanes": [
        {
          "id": "main",
          "label": "Lifecycle phases"
        },
        {
          "id": "waiting",
          "label": "Interruptions"
        },
        {
          "id": "recovery",
          "label": "Recovery loop",
          "tone": "exception"
        },
        {
          "id": "terminal",
          "label": "Terminal exits"
        }
      ],
      "nodes": [
        {
          "id": "queued",
          "type": "start",
          "lane": "main",
          "card": {
            "title": "Queued",
            "subtitle": "Request accepted"
          }
        },
        {
          "id": "planning",
          "type": "active",
          "lane": "main",
          "card": {
            "title": "Planning",
            "subtitle": "Build task graph"
          }
        },
        {
          "id": "executing",
          "type": "active",
          "lane": "main",
          "card": {
            "title": "Executing",
            "subtitle": "Tool calls"
          }
        },
        {
          "id": "reviewing",
          "type": "decision",
          "lane": "main",
          "card": {
            "title": "Reviewing",
            "subtitle": "Quality gate"
          }
        },
        {
          "id": "completed",
          "type": "success",
          "lane": "main",
          "card": {
            "title": "Completed",
            "subtitle": "Final response"
          }
        },
        {
          "id": "approval",
          "type": "waiting",
          "lane": "waiting",
          "card": {
            "title": "Needs approval",
            "subtitle": "Human gate",
            "tag": "pause"
          }
        },
        {
          "id": "blocked",
          "type": "waiting",
          "lane": "waiting",
          "card": {
            "title": "Blocked",
            "subtitle": "Missing input"
          }
        },
        {
          "id": "failed",
          "type": "failure",
          "lane": "recovery",
          "card": {
            "title": "Failed",
            "subtitle": "Recoverable error",
            "tag": "retryable"
          }
        },
        {
          "id": "cancelled",
          "type": "failure",
          "lane": "terminal",
          "card": {
            "title": "Cancelled",
            "subtitle": "User stopped"
          }
        },
        {
          "id": "expired",
          "type": "failure",
          "lane": "terminal",
          "card": {
            "title": "Expired",
            "subtitle": "Timeout"
          }
        }
      ],
      "edges": [
        {
          "id": "plan",
          "from": "queued",
          "to": "planning",
          "tone": "main"
        },
        {
          "id": "execute",
          "from": "planning",
          "to": "executing",
          "tone": "main"
        },
        {
          "id": "review",
          "from": "executing",
          "to": "reviewing",
          "tone": "main"
        },
        {
          "id": "complete",
          "from": "reviewing",
          "to": "completed",
          "tone": "main"
        },
        {
          "id": "needs-approval",
          "from": "executing",
          "to": "approval",
          "label": "risky op",
          "tone": "security"
        },
        {
          "id": "approved",
          "from": "approval",
          "to": "executing",
          "label": "approved",
          "kind": "return"
        },
        {
          "id": "review-blocked",
          "from": "reviewing",
          "to": "blocked",
          "label": "missing input"
        },
        {
          "id": "execution-failed",
          "from": "executing",
          "to": "failed",
          "label": "error",
          "tone": "error"
        },
        {
          "id": "retry",
          "from": "failed",
          "to": "executing",
          "label": "retry",
          "kind": "return"
        },
        {
          "id": "approval-cancelled",
          "from": "approval",
          "to": "cancelled",
          "label": "denied",
          "tone": "error"
        },
        {
          "id": "block-expired",
          "from": "blocked",
          "to": "expired",
          "label": "timeout",
          "tone": "error"
        }
      ],
      "notes": [
        {
          "title": "Main path and waits",
          "items": [
            "The run has five ordered phases from queue to completion",
            "Approval and missing input pause the run without ending it"
          ]
        },
        {
          "title": "Recovery and terminal exits",
          "items": [
            "Failed loops back while retry budget remains",
            "Cancelled and Expired are terminal exits with no return path"
          ]
        }
      ]
    },
    "nodes": {
      "queued": {
        "x": 212,
        "y": 60,
        "width": 176,
        "height": 60
      },
      "planning": {
        "x": 452,
        "y": 60,
        "width": 176,
        "height": 60
      },
      "executing": {
        "x": 692,
        "y": 60,
        "width": 176,
        "height": 60
      },
      "reviewing": {
        "x": 932,
        "y": 60,
        "width": 176,
        "height": 60
      },
      "completed": {
        "x": 1172,
        "y": 60,
        "width": 176,
        "height": 60
      },
      "approval": {
        "x": 692,
        "y": 184,
        "width": 176,
        "height": 84
      },
      "blocked": {
        "x": 932,
        "y": 196,
        "width": 176,
        "height": 60
      },
      "failed": {
        "x": 932,
        "y": 332,
        "width": 176,
        "height": 84
      },
      "cancelled": {
        "x": 692,
        "y": 480,
        "width": 176,
        "height": 60
      },
      "expired": {
        "x": 1172,
        "y": 480,
        "width": 176,
        "height": 60
      }
    },
    "groups": {},
    "edges": {
      "plan": [
        {
          "x": 388,
          "y": 90
        },
        {
          "x": 452,
          "y": 90
        }
      ],
      "execute": [
        {
          "x": 628,
          "y": 90
        },
        {
          "x": 692,
          "y": 90
        }
      ],
      "review": [
        {
          "x": 868,
          "y": 90
        },
        {
          "x": 932,
          "y": 90
        }
      ],
      "complete": [
        {
          "x": 1108,
          "y": 90
        },
        {
          "x": 1172,
          "y": 90
        }
      ],
      "needs-approval": [
        {
          "x": 780,
          "y": 120
        },
        {
          "x": 780,
          "y": 184
        }
      ],
      "approved": [
        {
          "x": 752,
          "y": 184
        },
        {
          "x": 752,
          "y": 120
        }
      ],
      "review-blocked": [
        {
          "x": 1020,
          "y": 120
        },
        {
          "x": 1020,
          "y": 196
        }
      ],
      "execution-failed": [
        {
          "x": 868,
          "y": 102
        },
        {
          "x": 912,
          "y": 102
        },
        {
          "x": 912,
          "y": 374
        },
        {
          "x": 932,
          "y": 374
        }
      ],
      "retry": [
        {
          "x": 932,
          "y": 362
        },
        {
          "x": 888,
          "y": 362
        },
        {
          "x": 888,
          "y": 114
        },
        {
          "x": 868,
          "y": 114
        }
      ],
      "approval-cancelled": [
        {
          "x": 780,
          "y": 268
        },
        {
          "x": 780,
          "y": 480
        }
      ],
      "block-expired": [
        {
          "x": 1108,
          "y": 226
        },
        {
          "x": 1204,
          "y": 226
        },
        {
          "x": 1204,
          "y": 480
        }
      ]
    },
    "lanes": {
      "main": {
        "x": 40,
        "y": 40,
        "width": 1340,
        "height": 108
      },
      "waiting": {
        "x": 40,
        "y": 164,
        "width": 1340,
        "height": 132
      },
      "recovery": {
        "x": 40,
        "y": 312,
        "width": 1340,
        "height": 132
      },
      "terminal": {
        "x": 40,
        "y": 460,
        "width": 1340,
        "height": 108
      }
    },
    "phases": {},
    "labels": {
      "needs-approval": {
        "x": 780,
        "y": 152
      },
      "approved": {
        "x": 715,
        "y": 152
      },
      "review-blocked": {
        "x": 1020,
        "y": 158
      },
      "execution-failed": {
        "x": 912,
        "y": 278.8
      },
      "retry": {
        "x": 888,
        "y": 312.4
      },
      "approval-cancelled": {
        "x": 780,
        "y": 374
      },
      "block-expired": {
        "x": 1204,
        "y": 353
      }
    },
    "bounds": {
      "width": 1420,
      "height": 608
    }
  },
  "deployment-release": {
    "draft": {
      "kind": "lifecycle",
      "title": "Deployment release lifecycle",
      "subtitle": "States of one release object",
      "lanes": [
        {
          "id": "main",
          "label": "Release phases"
        },
        {
          "id": "waiting",
          "label": "Approval and health wait"
        },
        {
          "id": "recovery",
          "label": "Rollback controller",
          "tone": "exception"
        },
        {
          "id": "terminal",
          "label": "Terminal exits"
        }
      ],
      "nodes": [
        {
          "id": "queued",
          "type": "start",
          "lane": "main",
          "card": {
            "title": "Queued",
            "subtitle": "Change accepted"
          }
        },
        {
          "id": "building",
          "type": "active",
          "lane": "main",
          "card": {
            "title": "Building",
            "subtitle": "Immutable image"
          }
        },
        {
          "id": "verifying",
          "type": "decision",
          "lane": "main",
          "card": {
            "title": "Verifying",
            "subtitle": "Tests and policy",
            "tag": "gate"
          }
        },
        {
          "id": "ready",
          "type": "waiting",
          "lane": "main",
          "card": {
            "title": "Ready",
            "subtitle": "Promotion pending"
          }
        },
        {
          "id": "live",
          "type": "success",
          "lane": "main",
          "card": {
            "title": "Live",
            "subtitle": "Production healthy"
          }
        },
        {
          "id": "approval",
          "type": "waiting",
          "lane": "waiting",
          "card": {
            "title": "Needs approval",
            "subtitle": "Release owner",
            "tag": "pause"
          }
        },
        {
          "id": "paused",
          "type": "waiting",
          "lane": "waiting",
          "card": {
            "title": "Health paused",
            "subtitle": "SLO regression"
          }
        },
        {
          "id": "rolling-back",
          "type": "active",
          "lane": "recovery",
          "card": {
            "title": "Rolling back",
            "subtitle": "Last good image",
            "tag": "automatic"
          }
        },
        {
          "id": "cancelled",
          "type": "failure",
          "lane": "terminal",
          "card": {
            "title": "Cancelled",
            "subtitle": "Approval denied"
          }
        },
        {
          "id": "failed",
          "type": "failure",
          "lane": "terminal",
          "card": {
            "title": "Failed",
            "subtitle": "Rollback failed"
          }
        },
        {
          "id": "rolled-back",
          "type": "success",
          "lane": "terminal",
          "card": {
            "title": "Rolled back",
            "subtitle": "Service restored"
          }
        }
      ],
      "edges": [
        {
          "id": "build",
          "from": "queued",
          "to": "building",
          "tone": "main"
        },
        {
          "id": "verify",
          "from": "building",
          "to": "verifying",
          "tone": "main"
        },
        {
          "id": "pass",
          "from": "verifying",
          "to": "ready",
          "tone": "main"
        },
        {
          "id": "promote",
          "from": "ready",
          "to": "live",
          "tone": "main"
        },
        {
          "id": "sign-off",
          "from": "verifying",
          "to": "approval",
          "label": "needs sign-off",
          "tone": "security"
        },
        {
          "id": "approved",
          "from": "approval",
          "to": "ready",
          "label": "approved"
        },
        {
          "id": "denied",
          "from": "approval",
          "to": "cancelled",
          "label": "denied",
          "tone": "error"
        },
        {
          "id": "abort",
          "from": "ready",
          "to": "rolling-back",
          "label": "abort",
          "tone": "error"
        },
        {
          "id": "rollback-failed",
          "from": "rolling-back",
          "to": "failed",
          "tone": "error"
        },
        {
          "id": "regress",
          "from": "live",
          "to": "paused",
          "label": "SLO regression",
          "kind": "async"
        },
        {
          "id": "rollback",
          "from": "paused",
          "to": "rolling-back",
          "label": "roll back"
        },
        {
          "id": "restored",
          "from": "rolling-back",
          "to": "rolled-back",
          "label": "restored",
          "tone": "main"
        }
      ],
      "notes": [
        {
          "title": "Promotion rail",
          "items": [
            "The release moves through five ordered phases",
            "Verification and approval remain distinct states",
            "Live means production health is currently proven"
          ]
        },
        {
          "title": "Explicit endings",
          "items": [
            "Denied approval ends as Cancelled",
            "A failed rollback ends as Failed",
            "A successful rollback is a terminal restored outcome"
          ]
        }
      ]
    },
    "nodes": {
      "queued": {
        "x": 212,
        "y": 72,
        "width": 176,
        "height": 60
      },
      "building": {
        "x": 452,
        "y": 72,
        "width": 176,
        "height": 60
      },
      "verifying": {
        "x": 692,
        "y": 60,
        "width": 176,
        "height": 84
      },
      "ready": {
        "x": 932,
        "y": 72,
        "width": 176,
        "height": 60
      },
      "live": {
        "x": 1172,
        "y": 72,
        "width": 176,
        "height": 60
      },
      "approval": {
        "x": 692,
        "y": 208,
        "width": 176,
        "height": 84
      },
      "paused": {
        "x": 1172,
        "y": 220,
        "width": 176,
        "height": 60
      },
      "rolling-back": {
        "x": 1172,
        "y": 356,
        "width": 176,
        "height": 84
      },
      "cancelled": {
        "x": 692,
        "y": 504,
        "width": 176,
        "height": 60
      },
      "failed": {
        "x": 1172,
        "y": 504,
        "width": 176,
        "height": 60
      },
      "rolled-back": {
        "x": 1172,
        "y": 608,
        "width": 176,
        "height": 60
      }
    },
    "groups": {},
    "edges": {
      "build": [
        {
          "x": 388,
          "y": 102
        },
        {
          "x": 452,
          "y": 102
        }
      ],
      "verify": [
        {
          "x": 628,
          "y": 102
        },
        {
          "x": 692,
          "y": 102
        }
      ],
      "pass": [
        {
          "x": 868,
          "y": 102
        },
        {
          "x": 932,
          "y": 102
        }
      ],
      "promote": [
        {
          "x": 1108,
          "y": 102
        },
        {
          "x": 1172,
          "y": 102
        }
      ],
      "sign-off": [
        {
          "x": 780,
          "y": 144
        },
        {
          "x": 780,
          "y": 208
        }
      ],
      "approved": [
        {
          "x": 868,
          "y": 250
        },
        {
          "x": 964,
          "y": 250
        },
        {
          "x": 964,
          "y": 132
        }
      ],
      "denied": [
        {
          "x": 780,
          "y": 292
        },
        {
          "x": 780,
          "y": 504
        }
      ],
      "abort": [
        {
          "x": 1076,
          "y": 132
        },
        {
          "x": 1076,
          "y": 398
        },
        {
          "x": 1172,
          "y": 398
        }
      ],
      "rollback-failed": [
        {
          "x": 1260,
          "y": 440
        },
        {
          "x": 1260,
          "y": 504
        }
      ],
      "regress": [
        {
          "x": 1260,
          "y": 132
        },
        {
          "x": 1260,
          "y": 220
        }
      ],
      "rollback": [
        {
          "x": 1260,
          "y": 280
        },
        {
          "x": 1260,
          "y": 356
        }
      ],
      "restored": [
        {
          "x": 1316,
          "y": 440
        },
        {
          "x": 1316,
          "y": 484
        },
        {
          "x": 1364,
          "y": 484
        },
        {
          "x": 1364,
          "y": 588
        },
        {
          "x": 1316,
          "y": 588
        },
        {
          "x": 1316,
          "y": 608
        }
      ]
    },
    "lanes": {
      "main": {
        "x": 40,
        "y": 40,
        "width": 1340,
        "height": 132
      },
      "waiting": {
        "x": 40,
        "y": 188,
        "width": 1340,
        "height": 132
      },
      "recovery": {
        "x": 40,
        "y": 336,
        "width": 1340,
        "height": 132
      },
      "terminal": {
        "x": 40,
        "y": 484,
        "width": 1340,
        "height": 212
      }
    },
    "phases": {},
    "labels": {
      "sign-off": {
        "x": 780,
        "y": 176
      },
      "approved": {
        "x": 916,
        "y": 250
      },
      "denied": {
        "x": 780,
        "y": 398
      },
      "abort": {
        "x": 1076,
        "y": 265
      },
      "regress": {
        "x": 1260,
        "y": 176
      },
      "rollback": {
        "x": 1260,
        "y": 318
      },
      "restored": {
        "x": 1398,
        "y": 536
      }
    },
    "bounds": {
      "width": 1420,
      "height": 736
    }
  },
  "production-deployment": {
    "draft": {
      "kind": "architecture",
      "density": "compact",
      "title": "Production deployment ownership",
      "subtitle": "Who runs what, and where traffic crosses",
      "direction": "RIGHT",
      "groups": [
        {
          "id": "us-east",
          "label": "AWS us-east-1 · production"
        },
        {
          "id": "private",
          "label": "Private application network",
          "parent": "us-east",
          "tone": "security"
        },
        {
          "id": "eu-west",
          "label": "AWS eu-west-1 · disaster recovery"
        }
      ],
      "nodes": [
        {
          "id": "clients",
          "type": "client",
          "card": {
            "title": "Customers",
            "subtitle": "Web and mobile"
          }
        },
        {
          "id": "edge",
          "type": "gateway",
          "group": "us-east",
          "card": {
            "title": "Global edge",
            "subtitle": "CDN and WAF",
            "brand": "cloudflare",
            "tag": "Platform"
          }
        },
        {
          "id": "gateway",
          "type": "security",
          "group": "us-east",
          "card": {
            "title": "API gateway",
            "subtitle": "Public :443",
            "tag": "Platform"
          }
        },
        {
          "id": "api-a",
          "type": "service",
          "group": "private",
          "card": {
            "title": "API pods · AZ-a",
            "subtitle": "Private subnet",
            "brand": "kubernetes",
            "tag": "Orders team"
          }
        },
        {
          "id": "api-b",
          "type": "service",
          "group": "private",
          "card": {
            "title": "API pods · AZ-b",
            "subtitle": "Private subnet",
            "brand": "kubernetes",
            "tag": "Orders team"
          }
        },
        {
          "id": "redis",
          "type": "cache",
          "group": "private",
          "card": {
            "title": "Redis",
            "subtitle": "Multi-AZ cache",
            "brand": "redis",
            "tag": "Platform"
          }
        },
        {
          "id": "postgres",
          "type": "database",
          "group": "private",
          "card": {
            "title": "PostgreSQL",
            "subtitle": "Primary, encrypted",
            "brand": "postgresql",
            "tag": "Data"
          }
        },
        {
          "id": "events",
          "type": "queue",
          "group": "private",
          "card": {
            "title": "Event bus",
            "subtitle": "orders.v1",
            "tag": "Platform"
          }
        },
        {
          "id": "workers",
          "type": "service",
          "group": "private",
          "card": {
            "title": "Workers",
            "subtitle": "Private workload",
            "tag": "Orders team"
          }
        },
        {
          "id": "audit",
          "type": "storage",
          "group": "us-east",
          "card": {
            "title": "Audit archive",
            "subtitle": "Immutable objects",
            "tag": "Security"
          }
        },
        {
          "id": "replica",
          "type": "database",
          "group": "eu-west",
          "card": {
            "title": "DR replica",
            "subtitle": "eu-west-1",
            "brand": "postgresql",
            "tag": "Data"
          }
        },
        {
          "id": "observability",
          "type": "external",
          "card": {
            "title": "Observability",
            "subtitle": "Metrics and traces",
            "tag": "SRE"
          }
        }
      ],
      "edges": [
        {
          "id": "e1",
          "from": "clients",
          "to": "edge",
          "label": "HTTPS",
          "tone": "main"
        },
        {
          "id": "e2",
          "from": "edge",
          "to": "gateway",
          "label": "mTLS",
          "tone": "security"
        },
        {
          "id": "e3",
          "from": "gateway",
          "to": "api-a",
          "label": "VPC route",
          "tone": "main"
        },
        {
          "id": "e4",
          "from": "gateway",
          "to": "api-b",
          "label": "VPC route",
          "tone": "main"
        },
        {
          "id": "e5",
          "from": "api-a",
          "to": "redis",
          "label": "cache"
        },
        {
          "id": "e6",
          "from": "api-b",
          "to": "postgres",
          "label": "SQL"
        },
        {
          "id": "e7",
          "from": "api-a",
          "to": "events",
          "label": "publish",
          "kind": "async"
        },
        {
          "id": "e8",
          "from": "api-b",
          "to": "events",
          "kind": "async"
        },
        {
          "id": "e9",
          "from": "events",
          "to": "workers",
          "tone": "main"
        },
        {
          "id": "e10",
          "from": "postgres",
          "to": "replica",
          "label": "cross-region WAL",
          "tone": "security"
        },
        {
          "id": "e11",
          "from": "workers",
          "to": "audit",
          "label": "evidence",
          "kind": "async"
        },
        {
          "id": "e12",
          "from": "workers",
          "to": "observability",
          "label": "OTLP",
          "kind": "async"
        }
      ],
      "views": [
        {
          "id": "crossings",
          "label": "Crossings",
          "caption": "Public HTTPS ends at the edge; mTLS crosses into the private network; WAL crosses regions.",
          "nodes": [
            "clients",
            "edge",
            "gateway",
            "postgres",
            "replica"
          ]
        },
        {
          "id": "async",
          "label": "Async work",
          "caption": "API pods publish to the event bus; workers drain it and leave evidence.",
          "nodes": [
            "api-a",
            "api-b",
            "events",
            "workers",
            "audit",
            "observability"
          ]
        }
      ],
      "notes": [
        {
          "title": "Runtime ownership",
          "items": [
            "Platform owns the edge, gateway, cache and event bus",
            "Application teams own API pods and workers",
            "Data owns primary and disaster-recovery state"
          ]
        },
        {
          "title": "Named crossings",
          "items": [
            "Public HTTPS terminates at the managed edge",
            "mTLS crosses into the application network",
            "Cross-region WAL is explicit and encrypted"
          ]
        }
      ]
    },
    "nodes": {
      "api-a": {
        "x": 858,
        "y": 240,
        "width": 176,
        "height": 84
      },
      "api-b": {
        "x": 858,
        "y": 136,
        "width": 176,
        "height": 84
      },
      "redis": {
        "x": 1114,
        "y": 344,
        "width": 176,
        "height": 84
      },
      "postgres": {
        "x": 1114,
        "y": 136,
        "width": 176,
        "height": 84
      },
      "events": {
        "x": 1114,
        "y": 240,
        "width": 176,
        "height": 84
      },
      "workers": {
        "x": 1370,
        "y": 240,
        "width": 176,
        "height": 84
      },
      "edge": {
        "x": 317,
        "y": 240,
        "width": 176,
        "height": 84
      },
      "gateway": {
        "x": 573,
        "y": 240,
        "width": 176,
        "height": 84
      },
      "audit": {
        "x": 1655,
        "y": 240,
        "width": 176,
        "height": 84
      },
      "replica": {
        "x": 1961,
        "y": 136,
        "width": 176,
        "height": 84
      },
      "clients": {
        "x": 40,
        "y": 252,
        "width": 176,
        "height": 60
      },
      "observability": {
        "x": 1937,
        "y": 302,
        "width": 176,
        "height": 84
      }
    },
    "groups": {
      "us-east": {
        "x": 293,
        "y": 40,
        "width": 1562,
        "height": 436
      },
      "private": {
        "x": 834,
        "y": 88,
        "width": 736,
        "height": 364
      },
      "eu-west": {
        "x": 1937,
        "y": 88,
        "width": 224,
        "height": 156
      }
    },
    "edges": {
      "e1": [
        {
          "x": 216,
          "y": 282
        },
        {
          "x": 317,
          "y": 282
        }
      ],
      "e2": [
        {
          "x": 493,
          "y": 282
        },
        {
          "x": 573,
          "y": 282
        }
      ],
      "e3": [
        {
          "x": 749,
          "y": 282
        },
        {
          "x": 858,
          "y": 282
        }
      ],
      "e4": [
        {
          "x": 749,
          "y": 282
        },
        {
          "x": 759,
          "y": 282
        },
        {
          "x": 759,
          "y": 178
        },
        {
          "x": 858,
          "y": 178
        }
      ],
      "e5": [
        {
          "x": 1034,
          "y": 282
        },
        {
          "x": 1044,
          "y": 282
        },
        {
          "x": 1044,
          "y": 386
        },
        {
          "x": 1114,
          "y": 386
        }
      ],
      "e6": [
        {
          "x": 1034,
          "y": 178
        },
        {
          "x": 1114,
          "y": 178
        }
      ],
      "e7": [
        {
          "x": 1034,
          "y": 282
        },
        {
          "x": 1114,
          "y": 282
        }
      ],
      "e8": [
        {
          "x": 1034,
          "y": 178
        },
        {
          "x": 1044,
          "y": 178
        },
        {
          "x": 1044,
          "y": 282
        },
        {
          "x": 1114,
          "y": 282
        }
      ],
      "e9": [
        {
          "x": 1290,
          "y": 282
        },
        {
          "x": 1370,
          "y": 282
        }
      ],
      "e10": [
        {
          "x": 1290,
          "y": 178
        },
        {
          "x": 1961,
          "y": 178
        }
      ],
      "e11": [
        {
          "x": 1546,
          "y": 282
        },
        {
          "x": 1655,
          "y": 282
        }
      ],
      "e12": [
        {
          "x": 1546,
          "y": 282
        },
        {
          "x": 1585,
          "y": 282
        },
        {
          "x": 1585,
          "y": 344
        },
        {
          "x": 1937,
          "y": 344
        }
      ]
    },
    "bounds": {
      "width": 2201,
      "height": 516
    },
    "labels": {
      "e1": {
        "x": 266.5,
        "y": 282
      },
      "e2": {
        "x": 533,
        "y": 282
      },
      "e3": {
        "x": 803.5,
        "y": 282
      },
      "e4": {
        "x": 808.5,
        "y": 178
      },
      "e5": {
        "x": 1079,
        "y": 386
      },
      "e6": {
        "x": 1074,
        "y": 178
      },
      "e7": {
        "x": 1074,
        "y": 282
      },
      "e10": {
        "x": 1625.5,
        "y": 178
      },
      "e11": {
        "x": 1600.5,
        "y": 282
      },
      "e12": {
        "x": 1761,
        "y": 344
      }
    }
  },
  "web-app": {
    "draft": {
      "kind": "architecture",
      "density": "compact",
      "title": "Sample web app",
      "subtitle": "Three tiers on AWS",
      "direction": "RIGHT",
      "groups": [
        {
          "id": "region",
          "label": "AWS us-west-2"
        },
        {
          "id": "sg-api",
          "label": "sg-api · :443 / :8000",
          "parent": "region",
          "tone": "security"
        }
      ],
      "nodes": [
        {
          "id": "users",
          "type": "client",
          "card": {
            "title": "Users",
            "subtitle": "Browser and mobile"
          }
        },
        {
          "id": "auth",
          "type": "security",
          "card": {
            "title": "Auth provider",
            "subtitle": "OAuth 2.0"
          }
        },
        {
          "id": "cdn",
          "type": "gateway",
          "group": "region",
          "card": {
            "title": "CloudFront",
            "subtitle": "CDN"
          }
        },
        {
          "id": "lb",
          "type": "gateway",
          "group": "sg-api",
          "card": {
            "title": "Load balancer",
            "subtitle": "HTTPS",
            "tag": ":443"
          }
        },
        {
          "id": "api",
          "type": "service",
          "group": "sg-api",
          "card": {
            "title": "API server",
            "subtitle": "FastAPI",
            "brand": "fastapi",
            "tag": ":8000"
          }
        },
        {
          "id": "cache",
          "type": "cache",
          "group": "region",
          "card": {
            "title": "Redis",
            "subtitle": "Read-through cache",
            "brand": "redis",
            "tag": ":6379"
          }
        },
        {
          "id": "db",
          "type": "database",
          "group": "region",
          "card": {
            "title": "PostgreSQL",
            "subtitle": "Primary",
            "brand": "postgresql",
            "tag": ":5432"
          }
        },
        {
          "id": "s3",
          "type": "storage",
          "group": "region",
          "card": {
            "title": "S3",
            "subtitle": "Static assets"
          }
        },
        {
          "id": "queue",
          "type": "queue",
          "group": "region",
          "card": {
            "title": "SQS",
            "subtitle": "Job queue"
          }
        },
        {
          "id": "worker",
          "type": "service",
          "group": "region",
          "card": {
            "title": "Worker",
            "subtitle": "Async jobs"
          }
        }
      ],
      "edges": [
        {
          "id": "e1",
          "from": "users",
          "to": "cdn",
          "label": "HTTPS",
          "tone": "main"
        },
        {
          "id": "e2",
          "from": "cdn",
          "to": "lb",
          "tone": "main"
        },
        {
          "id": "e3",
          "from": "cdn",
          "to": "s3",
          "label": "static",
          "kind": "async"
        },
        {
          "id": "e4",
          "from": "lb",
          "to": "api",
          "tone": "main"
        },
        {
          "id": "e5",
          "from": "auth",
          "to": "api",
          "label": "verify JWT",
          "tone": "security"
        },
        {
          "id": "e6",
          "from": "api",
          "to": "cache",
          "label": "read-through"
        },
        {
          "id": "e7",
          "from": "api",
          "to": "db",
          "label": "SQL",
          "tone": "main"
        },
        {
          "id": "e8",
          "from": "api",
          "to": "queue",
          "label": "enqueue",
          "kind": "async"
        },
        {
          "id": "e9",
          "from": "queue",
          "to": "worker"
        }
      ],
      "notes": [
        {
          "title": "Edge",
          "items": [
            "CloudFront fronts all traffic",
            "S3 serves static assets"
          ]
        },
        {
          "title": "Security",
          "items": [
            "OAuth 2.0 with JWT and PKCE",
            "API and load balancer isolated in a security group"
          ]
        }
      ]
    },
    "nodes": {
      "lb": {
        "x": 602,
        "y": 216,
        "width": 176,
        "height": 84
      },
      "api": {
        "x": 858,
        "y": 216,
        "width": 176,
        "height": 84
      },
      "cdn": {
        "x": 317,
        "y": 88,
        "width": 176,
        "height": 60
      },
      "cache": {
        "x": 1143,
        "y": 124,
        "width": 176,
        "height": 84
      },
      "db": {
        "x": 1143,
        "y": 308,
        "width": 176,
        "height": 84
      },
      "s3": {
        "x": 578,
        "y": 88,
        "width": 176,
        "height": 60
      },
      "queue": {
        "x": 1143,
        "y": 228,
        "width": 176,
        "height": 60
      },
      "worker": {
        "x": 1399,
        "y": 228,
        "width": 176,
        "height": 60
      },
      "users": {
        "x": 40,
        "y": 88,
        "width": 176,
        "height": 60
      },
      "auth": {
        "x": 40,
        "y": 290,
        "width": 176,
        "height": 60
      }
    },
    "groups": {
      "region": {
        "x": 293,
        "y": 40,
        "width": 1306,
        "height": 376
      },
      "sg-api": {
        "x": 578,
        "y": 168,
        "width": 480,
        "height": 177
      }
    },
    "edges": {
      "e1": [
        {
          "x": 216,
          "y": 118
        },
        {
          "x": 317,
          "y": 118
        }
      ],
      "e2": [
        {
          "x": 493,
          "y": 118
        },
        {
          "x": 503,
          "y": 118
        },
        {
          "x": 503,
          "y": 258
        },
        {
          "x": 602,
          "y": 258
        }
      ],
      "e3": [
        {
          "x": 493,
          "y": 118
        },
        {
          "x": 578,
          "y": 118
        }
      ],
      "e4": [
        {
          "x": 778,
          "y": 258
        },
        {
          "x": 858,
          "y": 258
        }
      ],
      "e5": [
        {
          "x": 216,
          "y": 320
        },
        {
          "x": 788,
          "y": 320
        },
        {
          "x": 788,
          "y": 258
        },
        {
          "x": 858,
          "y": 258
        }
      ],
      "e6": [
        {
          "x": 1034,
          "y": 258
        },
        {
          "x": 1073,
          "y": 258
        },
        {
          "x": 1073,
          "y": 166
        },
        {
          "x": 1143,
          "y": 166
        }
      ],
      "e7": [
        {
          "x": 1034,
          "y": 258
        },
        {
          "x": 1073,
          "y": 258
        },
        {
          "x": 1073,
          "y": 350
        },
        {
          "x": 1143,
          "y": 350
        }
      ],
      "e8": [
        {
          "x": 1034,
          "y": 258
        },
        {
          "x": 1143,
          "y": 258
        }
      ],
      "e9": [
        {
          "x": 1319,
          "y": 258
        },
        {
          "x": 1399,
          "y": 258
        }
      ]
    },
    "bounds": {
      "width": 1639,
      "height": 456
    },
    "labels": {
      "e1": {
        "x": 266.5,
        "y": 118
      },
      "e3": {
        "x": 535.5,
        "y": 118
      },
      "e5": {
        "x": 502,
        "y": 320
      },
      "e6": {
        "x": 1073,
        "y": 198.2
      },
      "e7": {
        "x": 1108,
        "y": 350
      },
      "e8": {
        "x": 1088.5,
        "y": 258
      }
    }
  },
  "product-analytics": {
    "draft": {
      "kind": "dataflow",
      "density": "compact",
      "title": "Product analytics",
      "subtitle": "From SDK events to dashboards and models",
      "direction": "RIGHT",
      "phases": [
        {
          "id": "sources",
          "label": "Sources",
          "nodes": [
            "web",
            "mobile"
          ]
        },
        {
          "id": "ingest",
          "label": "Ingest",
          "nodes": [
            "edge"
          ]
        },
        {
          "id": "process",
          "label": "Process",
          "nodes": [
            "consent",
            "stream"
          ]
        },
        {
          "id": "store",
          "label": "Store",
          "nodes": [
            "pii",
            "warehouse",
            "features"
          ]
        },
        {
          "id": "consume",
          "label": "Consume",
          "nodes": [
            "dashboards",
            "model"
          ]
        }
      ],
      "nodes": [
        {
          "id": "web",
          "type": "client",
          "card": {
            "title": "Web app",
            "subtitle": "Browser SDK"
          }
        },
        {
          "id": "mobile",
          "type": "client",
          "card": {
            "title": "Mobile",
            "subtitle": "iOS and Android"
          }
        },
        {
          "id": "edge",
          "type": "gateway",
          "card": {
            "title": "Edge API",
            "subtitle": "Collector"
          }
        },
        {
          "id": "consent",
          "type": "security",
          "card": {
            "title": "Consent gate",
            "subtitle": "Policy filter"
          }
        },
        {
          "id": "stream",
          "type": "queue",
          "card": {
            "title": "Event stream",
            "subtitle": "Kafka topic"
          }
        },
        {
          "id": "pii",
          "type": "security",
          "card": {
            "title": "PII vault",
            "subtitle": "Encrypted"
          }
        },
        {
          "id": "warehouse",
          "type": "database",
          "card": {
            "title": "Warehouse",
            "subtitle": "Analytics tables",
            "brand": "snowflake"
          }
        },
        {
          "id": "features",
          "type": "database",
          "card": {
            "title": "Feature store",
            "subtitle": "Daily batch"
          }
        },
        {
          "id": "dashboards",
          "type": "service",
          "card": {
            "title": "Dashboards",
            "subtitle": "Product metrics"
          }
        },
        {
          "id": "model",
          "type": "service",
          "card": {
            "title": "ML model",
            "subtitle": "Ranking job"
          }
        }
      ],
      "edges": [
        {
          "id": "e1",
          "from": "web",
          "to": "edge",
          "label": "clickstream",
          "tone": "main"
        },
        {
          "id": "e2",
          "from": "mobile",
          "to": "edge",
          "label": "app events"
        },
        {
          "id": "e3",
          "from": "edge",
          "to": "consent",
          "label": "identity",
          "tone": "security"
        },
        {
          "id": "e4",
          "from": "edge",
          "to": "stream",
          "label": "accepted events",
          "tone": "main"
        },
        {
          "id": "e5",
          "from": "consent",
          "to": "pii",
          "label": "identity map",
          "tone": "security"
        },
        {
          "id": "e6",
          "from": "stream",
          "to": "warehouse",
          "label": "normalized facts",
          "tone": "main"
        },
        {
          "id": "e7",
          "from": "warehouse",
          "to": "features",
          "label": "daily aggregates",
          "kind": "async"
        },
        {
          "id": "e8",
          "from": "warehouse",
          "to": "dashboards",
          "label": "metrics SQL"
        },
        {
          "id": "e9",
          "from": "features",
          "to": "model",
          "label": "feature vectors",
          "kind": "async"
        },
        {
          "id": "e10",
          "from": "pii",
          "to": "dashboards",
          "label": "restricted join",
          "tone": "security"
        }
      ],
      "notes": [
        {
          "title": "Sensitive boundary",
          "items": [
            "Consent and PII paths are security flows",
            "PII lands in a restricted vault, apart from the warehouse",
            "Restricted joins are visible without implying default access"
          ]
        }
      ]
    },
    "nodes": {
      "web": {
        "x": 40,
        "y": 84,
        "width": 176,
        "height": 60
      },
      "mobile": {
        "x": 40,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "edge": {
        "x": 344,
        "y": 84,
        "width": 176,
        "height": 60
      },
      "consent": {
        "x": 648,
        "y": 84,
        "width": 176,
        "height": 60
      },
      "stream": {
        "x": 648,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "pii": {
        "x": 952,
        "y": 84,
        "width": 176,
        "height": 60
      },
      "warehouse": {
        "x": 952,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "features": {
        "x": 1256,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "dashboards": {
        "x": 1560,
        "y": 84,
        "width": 176,
        "height": 60
      },
      "model": {
        "x": 1560,
        "y": 184,
        "width": 176,
        "height": 60
      }
    },
    "groups": {},
    "edges": {
      "e1": [
        {
          "x": 216,
          "y": 114
        },
        {
          "x": 344,
          "y": 114
        }
      ],
      "e2": [
        {
          "x": 216,
          "y": 214
        },
        {
          "x": 240,
          "y": 214
        },
        {
          "x": 240,
          "y": 114
        },
        {
          "x": 344,
          "y": 114
        }
      ],
      "e3": [
        {
          "x": 520,
          "y": 114
        },
        {
          "x": 648,
          "y": 114
        }
      ],
      "e4": [
        {
          "x": 520,
          "y": 114
        },
        {
          "x": 544,
          "y": 114
        },
        {
          "x": 544,
          "y": 214
        },
        {
          "x": 648,
          "y": 214
        }
      ],
      "e5": [
        {
          "x": 824,
          "y": 114
        },
        {
          "x": 952,
          "y": 114
        }
      ],
      "e6": [
        {
          "x": 824,
          "y": 214
        },
        {
          "x": 952,
          "y": 214
        }
      ],
      "e7": [
        {
          "x": 1128,
          "y": 214
        },
        {
          "x": 1256,
          "y": 214
        }
      ],
      "e8": [
        {
          "x": 1128,
          "y": 214
        },
        {
          "x": 1152,
          "y": 214
        },
        {
          "x": 1152,
          "y": 114
        },
        {
          "x": 1560,
          "y": 114
        }
      ],
      "e9": [
        {
          "x": 1432,
          "y": 214
        },
        {
          "x": 1560,
          "y": 214
        }
      ],
      "e10": [
        {
          "x": 1128,
          "y": 114
        },
        {
          "x": 1560,
          "y": 114
        }
      ]
    },
    "bounds": {
      "width": 1776,
      "height": 284
    },
    "phases": {
      "sources": {
        "x": 20,
        "y": 20,
        "width": 216,
        "height": 244
      },
      "ingest": {
        "x": 324,
        "y": 20,
        "width": 216,
        "height": 244
      },
      "process": {
        "x": 628,
        "y": 20,
        "width": 216,
        "height": 244
      },
      "store": {
        "x": 932,
        "y": 20,
        "width": 520,
        "height": 244
      },
      "consume": {
        "x": 1540,
        "y": 20,
        "width": 216,
        "height": 244
      }
    },
    "labels": {
      "e1": {
        "x": 280,
        "y": 114
      },
      "e2": {
        "x": 240,
        "y": 164
      },
      "e3": {
        "x": 584,
        "y": 114
      },
      "e4": {
        "x": 544,
        "y": 164
      },
      "e5": {
        "x": 888,
        "y": 114
      },
      "e6": {
        "x": 888,
        "y": 214
      },
      "e7": {
        "x": 1192,
        "y": 214
      },
      "e8": {
        "x": 1356,
        "y": 114
      },
      "e9": {
        "x": 1496,
        "y": 214
      },
      "e10": {
        "x": 1214.4,
        "y": 114
      }
    }
  },
  "event-stream": {
    "draft": {
      "kind": "dataflow",
      "density": "compact",
      "title": "Order event-stream topology",
      "subtitle": "Topics, consumer groups and the dead-letter path",
      "direction": "RIGHT",
      "phases": [
        {
          "id": "producers",
          "label": "Producers",
          "nodes": [
            "checkout",
            "billing"
          ]
        },
        {
          "id": "transit",
          "label": "Transit",
          "nodes": [
            "orders",
            "payments"
          ]
        },
        {
          "id": "processors",
          "label": "Processors",
          "nodes": [
            "validate",
            "enrich"
          ]
        },
        {
          "id": "state",
          "label": "State and recovery",
          "nodes": [
            "order-state",
            "dlq"
          ]
        },
        {
          "id": "consumers",
          "label": "Consumers",
          "nodes": [
            "fulfillment",
            "analytics",
            "replay",
            "ops"
          ]
        }
      ],
      "nodes": [
        {
          "id": "checkout",
          "type": "service",
          "card": {
            "title": "Checkout API",
            "subtitle": "Order producer"
          }
        },
        {
          "id": "billing",
          "type": "service",
          "card": {
            "title": "Billing API",
            "subtitle": "Payment producer",
            "brand": "stripe"
          }
        },
        {
          "id": "orders",
          "type": "queue",
          "card": {
            "title": "orders.v1",
            "subtitle": "Topic",
            "tag": "12 partitions"
          }
        },
        {
          "id": "payments",
          "type": "queue",
          "card": {
            "title": "payments.v2",
            "subtitle": "Topic",
            "tag": "8 partitions"
          }
        },
        {
          "id": "validate",
          "type": "service",
          "card": {
            "title": "Order validate",
            "subtitle": "Group fulfillment"
          }
        },
        {
          "id": "enrich",
          "type": "service",
          "card": {
            "title": "Payment enrich",
            "subtitle": "Group analytics"
          }
        },
        {
          "id": "order-state",
          "type": "database",
          "card": {
            "title": "Order state",
            "subtitle": "Materialized view"
          }
        },
        {
          "id": "dlq",
          "type": "queue",
          "card": {
            "title": "events.dlq",
            "subtitle": "Poison events"
          }
        },
        {
          "id": "fulfillment",
          "type": "service",
          "card": {
            "title": "Fulfillment",
            "subtitle": "Shipping workflow"
          }
        },
        {
          "id": "analytics",
          "type": "database",
          "card": {
            "title": "Analytics",
            "subtitle": "Streaming facts"
          }
        },
        {
          "id": "replay",
          "type": "security",
          "card": {
            "title": "Replay tool",
            "subtitle": "Approved batch"
          }
        },
        {
          "id": "ops",
          "type": "external",
          "card": {
            "title": "On-call",
            "subtitle": "DLQ owner",
            "brand": "pagerduty"
          }
        }
      ],
      "edges": [
        {
          "id": "e1",
          "from": "checkout",
          "to": "orders",
          "label": "OrderPlaced",
          "tone": "main"
        },
        {
          "id": "e2",
          "from": "billing",
          "to": "payments",
          "label": "PaymentCaptured",
          "tone": "main"
        },
        {
          "id": "e3",
          "from": "orders",
          "to": "validate",
          "label": "ordered",
          "tone": "main"
        },
        {
          "id": "e4",
          "from": "payments",
          "to": "enrich",
          "label": "payment facts",
          "tone": "main"
        },
        {
          "id": "e5",
          "from": "validate",
          "to": "order-state",
          "label": "valid order",
          "tone": "main"
        },
        {
          "id": "e6",
          "from": "enrich",
          "to": "order-state",
          "label": "enriched"
        },
        {
          "id": "e7",
          "from": "order-state",
          "to": "fulfillment",
          "label": "ready orders",
          "tone": "main"
        },
        {
          "id": "e8",
          "from": "order-state",
          "to": "analytics",
          "label": "order facts"
        },
        {
          "id": "e9",
          "from": "validate",
          "to": "dlq",
          "label": "invalid",
          "tone": "error"
        },
        {
          "id": "e10",
          "from": "enrich",
          "to": "dlq",
          "label": "poison",
          "tone": "error"
        },
        {
          "id": "e11",
          "from": "dlq",
          "to": "ops",
          "label": "sample",
          "tone": "error"
        },
        {
          "id": "e12",
          "from": "dlq",
          "to": "replay",
          "label": "approved replay",
          "kind": "async"
        }
      ],
      "notes": [
        {
          "title": "Failure ownership",
          "items": [
            "Poison events land in a retained dead-letter topic",
            "On-call inspects samples before replay",
            "Replay is gated, batched and auditable"
          ]
        }
      ]
    },
    "nodes": {
      "checkout": {
        "x": 40,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "billing": {
        "x": 40,
        "y": 308,
        "width": 176,
        "height": 60
      },
      "orders": {
        "x": 350,
        "y": 172,
        "width": 176,
        "height": 84
      },
      "payments": {
        "x": 350,
        "y": 296,
        "width": 176,
        "height": 84
      },
      "validate": {
        "x": 660,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "enrich": {
        "x": 660,
        "y": 284,
        "width": 176,
        "height": 60
      },
      "order-state": {
        "x": 970,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "dlq": {
        "x": 970,
        "y": 284,
        "width": 176,
        "height": 60
      },
      "fulfillment": {
        "x": 1280,
        "y": 84,
        "width": 176,
        "height": 60
      },
      "analytics": {
        "x": 1280,
        "y": 184,
        "width": 176,
        "height": 60
      },
      "replay": {
        "x": 1280,
        "y": 284,
        "width": 176,
        "height": 60
      },
      "ops": {
        "x": 1280,
        "y": 384,
        "width": 176,
        "height": 60
      }
    },
    "groups": {},
    "edges": {
      "e1": [
        {
          "x": 216,
          "y": 214
        },
        {
          "x": 350,
          "y": 214
        }
      ],
      "e2": [
        {
          "x": 216,
          "y": 338
        },
        {
          "x": 350,
          "y": 338
        }
      ],
      "e3": [
        {
          "x": 526,
          "y": 214
        },
        {
          "x": 660,
          "y": 214
        }
      ],
      "e4": [
        {
          "x": 526,
          "y": 338
        },
        {
          "x": 550,
          "y": 338
        },
        {
          "x": 550,
          "y": 314
        },
        {
          "x": 660,
          "y": 314
        }
      ],
      "e5": [
        {
          "x": 836,
          "y": 214
        },
        {
          "x": 970,
          "y": 214
        }
      ],
      "e6": [
        {
          "x": 836,
          "y": 314
        },
        {
          "x": 860,
          "y": 314
        },
        {
          "x": 860,
          "y": 214
        },
        {
          "x": 970,
          "y": 214
        }
      ],
      "e7": [
        {
          "x": 1146,
          "y": 214
        },
        {
          "x": 1170,
          "y": 214
        },
        {
          "x": 1170,
          "y": 114
        },
        {
          "x": 1280,
          "y": 114
        }
      ],
      "e8": [
        {
          "x": 1146,
          "y": 214
        },
        {
          "x": 1280,
          "y": 214
        }
      ],
      "e9": [
        {
          "x": 836,
          "y": 214
        },
        {
          "x": 860,
          "y": 214
        },
        {
          "x": 860,
          "y": 314
        },
        {
          "x": 970,
          "y": 314
        }
      ],
      "e10": [
        {
          "x": 836,
          "y": 314
        },
        {
          "x": 970,
          "y": 314
        }
      ],
      "e11": [
        {
          "x": 1146,
          "y": 314
        },
        {
          "x": 1170,
          "y": 314
        },
        {
          "x": 1170,
          "y": 414
        },
        {
          "x": 1280,
          "y": 414
        }
      ],
      "e12": [
        {
          "x": 1146,
          "y": 314
        },
        {
          "x": 1280,
          "y": 314
        }
      ]
    },
    "bounds": {
      "width": 1496,
      "height": 484
    },
    "phases": {
      "producers": {
        "x": 20,
        "y": 20,
        "width": 216,
        "height": 444
      },
      "transit": {
        "x": 330,
        "y": 20,
        "width": 216,
        "height": 444
      },
      "processors": {
        "x": 640,
        "y": 20,
        "width": 216,
        "height": 444
      },
      "state": {
        "x": 950,
        "y": 20,
        "width": 216,
        "height": 444
      },
      "consumers": {
        "x": 1260,
        "y": 20,
        "width": 216,
        "height": 444
      }
    },
    "labels": {
      "e1": {
        "x": 283,
        "y": 214
      },
      "e2": {
        "x": 283,
        "y": 338
      },
      "e3": {
        "x": 593,
        "y": 214
      },
      "e4": {
        "x": 605,
        "y": 314
      },
      "e5": {
        "x": 903,
        "y": 214
      },
      "e6": {
        "x": 860,
        "y": 264
      },
      "e7": {
        "x": 1225,
        "y": 114
      },
      "e8": {
        "x": 1213,
        "y": 214
      },
      "e9": {
        "x": 915,
        "y": 314
      },
      "e10": {
        "x": 862.8,
        "y": 314
      },
      "e11": {
        "x": 1225,
        "y": 414
      },
      "e12": {
        "x": 1213,
        "y": 314
      }
    }
  }
};
