// Generated by packages/layout/scripts/layout-samples.ts — do not edit.
import type { LaidOutDiagram } from '@stackmap/core';

export const groupedPlatformLayout: LaidOutDiagram = {
  "draft": {
    "kind": "architecture",
    "title": "Platform",
    "subtitle": "Grouped tiers",
    "direction": "DOWN",
    "groups": [
      {
        "id": "edge-tier",
        "label": "Edge"
      },
      {
        "id": "app-tier",
        "label": "App tier"
      },
      {
        "id": "data-tier",
        "label": "Data tier"
      }
    ],
    "nodes": [
      {
        "id": "web",
        "type": "client",
        "card": {
          "title": "Web app",
          "subtitle": "Next.js",
          "brand": "nextdotjs"
        }
      },
      {
        "id": "gw",
        "type": "gateway",
        "group": "edge-tier",
        "card": {
          "title": "API Gateway",
          "subtitle": "nginx",
          "brand": "nginx"
        }
      },
      {
        "id": "auth",
        "type": "security",
        "group": "edge-tier",
        "card": {
          "title": "Auth",
          "subtitle": "OIDC provider"
        }
      },
      {
        "id": "orders-svc",
        "type": "service",
        "group": "app-tier",
        "card": {
          "title": "orders",
          "subtitle": "Service"
        }
      },
      {
        "id": "billing-svc",
        "type": "service",
        "group": "app-tier",
        "card": {
          "title": "billing",
          "subtitle": "Service"
        }
      },
      {
        "id": "jobs",
        "type": "queue",
        "group": "app-tier",
        "card": {
          "title": "jobs",
          "subtitle": "RabbitMQ",
          "brand": "rabbitmq"
        }
      },
      {
        "id": "db",
        "type": "database",
        "group": "data-tier",
        "card": {
          "title": "postgres",
          "subtitle": "PostgreSQL",
          "brand": "postgresql"
        }
      },
      {
        "id": "kv",
        "type": "cache",
        "group": "data-tier",
        "card": {
          "title": "redis",
          "subtitle": "Redis",
          "brand": "redis"
        }
      },
      {
        "id": "blobs",
        "type": "storage",
        "group": "data-tier",
        "card": {
          "title": "assets",
          "subtitle": "Object storage"
        }
      },
      {
        "id": "stripe",
        "type": "external",
        "card": {
          "title": "Stripe",
          "subtitle": "Payments API",
          "brand": "stripe"
        }
      }
    ],
    "edges": [
      {
        "id": "e1",
        "from": "web",
        "to": "gw",
        "label": "HTTPS"
      },
      {
        "id": "e2",
        "from": "gw",
        "to": "auth"
      },
      {
        "id": "e3",
        "from": "gw",
        "to": "orders-svc"
      },
      {
        "id": "e4",
        "from": "gw",
        "to": "billing-svc"
      },
      {
        "id": "e5",
        "from": "orders-svc",
        "to": "jobs",
        "kind": "async",
        "label": "enqueue"
      },
      {
        "id": "e6",
        "from": "orders-svc",
        "to": "db"
      },
      {
        "id": "e7",
        "from": "orders-svc",
        "to": "kv"
      },
      {
        "id": "e8",
        "from": "billing-svc",
        "to": "db"
      },
      {
        "id": "e9",
        "from": "billing-svc",
        "to": "stripe"
      },
      {
        "id": "e10",
        "from": "jobs",
        "to": "blobs",
        "kind": "async"
      }
    ]
  },
  "nodes": {
    "gw": {
      "x": 204,
      "y": 229,
      "width": 280,
      "height": 64
    },
    "auth": {
      "x": 204,
      "y": 373,
      "width": 280,
      "height": 64
    },
    "orders-svc": {
      "x": 364,
      "y": 591,
      "width": 280,
      "height": 64
    },
    "billing-svc": {
      "x": 664,
      "y": 591,
      "width": 280,
      "height": 64
    },
    "jobs": {
      "x": 364,
      "y": 735,
      "width": 280,
      "height": 64
    },
    "db": {
      "x": 664,
      "y": 953,
      "width": 280,
      "height": 64
    },
    "kv": {
      "x": 364,
      "y": 953,
      "width": 280,
      "height": 64
    },
    "blobs": {
      "x": 64,
      "y": 953,
      "width": 280,
      "height": 64
    },
    "web": {
      "x": 204,
      "y": 40,
      "width": 280,
      "height": 64
    },
    "stripe": {
      "x": 1008,
      "y": 905,
      "width": 280,
      "height": 64
    }
  },
  "groups": {
    "edge-tier": {
      "x": 180,
      "y": 181,
      "width": 349,
      "height": 280
    },
    "app-tier": {
      "x": 340,
      "y": 543,
      "width": 628,
      "height": 280
    },
    "data-tier": {
      "x": 40,
      "y": 905,
      "width": 928,
      "height": 136
    }
  },
  "edges": {
    "e1": [
      {
        "x": 344,
        "y": 104
      },
      {
        "x": 344,
        "y": 229
      }
    ],
    "e2": [
      {
        "x": 344,
        "y": 293
      },
      {
        "x": 344,
        "y": 373
      }
    ],
    "e3": [
      {
        "x": 344,
        "y": 293
      },
      {
        "x": 344,
        "y": 303
      },
      {
        "x": 504,
        "y": 303
      },
      {
        "x": 504,
        "y": 591
      }
    ],
    "e4": [
      {
        "x": 344,
        "y": 293
      },
      {
        "x": 344,
        "y": 303
      },
      {
        "x": 504,
        "y": 303
      },
      {
        "x": 504,
        "y": 490
      },
      {
        "x": 804,
        "y": 490
      },
      {
        "x": 804,
        "y": 591
      }
    ],
    "e5": [
      {
        "x": 504,
        "y": 655
      },
      {
        "x": 504,
        "y": 735
      }
    ],
    "e6": [
      {
        "x": 504,
        "y": 655
      },
      {
        "x": 504,
        "y": 665
      },
      {
        "x": 664,
        "y": 665
      },
      {
        "x": 664,
        "y": 862
      },
      {
        "x": 804,
        "y": 862
      },
      {
        "x": 804,
        "y": 953
      }
    ],
    "e7": [
      {
        "x": 504,
        "y": 655
      },
      {
        "x": 504,
        "y": 665
      },
      {
        "x": 664,
        "y": 665
      },
      {
        "x": 664,
        "y": 862
      },
      {
        "x": 504,
        "y": 862
      },
      {
        "x": 504,
        "y": 953
      }
    ],
    "e8": [
      {
        "x": 804,
        "y": 655
      },
      {
        "x": 804,
        "y": 953
      }
    ],
    "e9": [
      {
        "x": 804,
        "y": 655
      },
      {
        "x": 804,
        "y": 862
      },
      {
        "x": 1148,
        "y": 862
      },
      {
        "x": 1148,
        "y": 905
      }
    ],
    "e10": [
      {
        "x": 504,
        "y": 799
      },
      {
        "x": 504,
        "y": 852
      },
      {
        "x": 204,
        "y": 852
      },
      {
        "x": 204,
        "y": 953
      }
    ]
  },
  "bounds": {
    "width": 1328,
    "height": 1081
  }
};
