// Generated by packages/layout/scripts/layout-samples.ts — do not edit.
import type { LaidOutDiagram } from '@stackmap/core';

export const groupedPlatformLayout: LaidOutDiagram = {
  "draft": {
    "kind": "architecture",
    "title": "Platform",
    "subtitle": "Grouped tiers",
    "direction": "RIGHT",
    "groups": [
      {
        "id": "edge-tier",
        "label": "Edge"
      },
      {
        "id": "app-tier",
        "label": "App tier"
      },
      {
        "id": "data-tier",
        "label": "Data tier"
      }
    ],
    "nodes": [
      {
        "id": "web",
        "type": "client",
        "card": {
          "title": "Web app",
          "subtitle": "Next.js",
          "brand": "nextdotjs"
        }
      },
      {
        "id": "gw",
        "type": "gateway",
        "group": "edge-tier",
        "card": {
          "title": "API Gateway",
          "subtitle": "nginx",
          "brand": "nginx"
        }
      },
      {
        "id": "auth",
        "type": "security",
        "group": "edge-tier",
        "card": {
          "title": "Auth",
          "subtitle": "OIDC provider"
        }
      },
      {
        "id": "orders-svc",
        "type": "service",
        "group": "app-tier",
        "card": {
          "title": "orders",
          "subtitle": "Service"
        }
      },
      {
        "id": "billing-svc",
        "type": "service",
        "group": "app-tier",
        "card": {
          "title": "billing",
          "subtitle": "Service"
        }
      },
      {
        "id": "jobs",
        "type": "queue",
        "group": "app-tier",
        "card": {
          "title": "jobs",
          "subtitle": "RabbitMQ",
          "brand": "rabbitmq"
        }
      },
      {
        "id": "db",
        "type": "database",
        "group": "data-tier",
        "card": {
          "title": "postgres",
          "subtitle": "PostgreSQL",
          "brand": "postgresql"
        }
      },
      {
        "id": "kv",
        "type": "cache",
        "group": "data-tier",
        "card": {
          "title": "redis",
          "subtitle": "Redis",
          "brand": "redis"
        }
      },
      {
        "id": "blobs",
        "type": "storage",
        "group": "data-tier",
        "card": {
          "title": "assets",
          "subtitle": "Object storage"
        }
      },
      {
        "id": "stripe",
        "type": "external",
        "card": {
          "title": "Stripe",
          "subtitle": "Payments API",
          "brand": "stripe"
        }
      }
    ],
    "edges": [
      {
        "id": "e1",
        "from": "web",
        "to": "gw",
        "label": "HTTPS"
      },
      {
        "id": "e2",
        "from": "gw",
        "to": "auth"
      },
      {
        "id": "e3",
        "from": "gw",
        "to": "orders-svc"
      },
      {
        "id": "e4",
        "from": "gw",
        "to": "billing-svc"
      },
      {
        "id": "e5",
        "from": "orders-svc",
        "to": "jobs",
        "kind": "async",
        "label": "enqueue"
      },
      {
        "id": "e6",
        "from": "orders-svc",
        "to": "db"
      },
      {
        "id": "e7",
        "from": "orders-svc",
        "to": "kv"
      },
      {
        "id": "e8",
        "from": "billing-svc",
        "to": "db"
      },
      {
        "id": "e9",
        "from": "billing-svc",
        "to": "stripe"
      },
      {
        "id": "e10",
        "from": "jobs",
        "to": "blobs",
        "kind": "async"
      }
    ]
  },
  "nodes": {
    "gw": {
      "x": 469,
      "y": 130,
      "width": 280,
      "height": 64
    },
    "auth": {
      "x": 769,
      "y": 130,
      "width": 280,
      "height": 64
    },
    "orders-svc": {
      "x": 1227,
      "y": 172,
      "width": 280,
      "height": 64
    },
    "billing-svc": {
      "x": 1227,
      "y": 256,
      "width": 280,
      "height": 64
    },
    "jobs": {
      "x": 1527,
      "y": 172,
      "width": 280,
      "height": 64
    },
    "db": {
      "x": 1985,
      "y": 256,
      "width": 280,
      "height": 64
    },
    "kv": {
      "x": 1985,
      "y": 172,
      "width": 280,
      "height": 64
    },
    "blobs": {
      "x": 1985,
      "y": 88,
      "width": 280,
      "height": 64
    },
    "web": {
      "x": 40,
      "y": 130,
      "width": 280,
      "height": 64
    },
    "stripe": {
      "x": 1961,
      "y": 384,
      "width": 280,
      "height": 64
    }
  },
  "groups": {
    "edge-tier": {
      "x": 445,
      "y": 82,
      "width": 628,
      "height": 147
    },
    "app-tier": {
      "x": 1203,
      "y": 124,
      "width": 628,
      "height": 220
    },
    "data-tier": {
      "x": 1961,
      "y": 40,
      "width": 328,
      "height": 304
    }
  },
  "edges": {
    "e1": [
      {
        "x": 320,
        "y": 162
      },
      {
        "x": 469,
        "y": 162
      }
    ],
    "e2": [
      {
        "x": 749,
        "y": 162
      },
      {
        "x": 769,
        "y": 162
      }
    ],
    "e3": [
      {
        "x": 749,
        "y": 162
      },
      {
        "x": 759,
        "y": 162
      },
      {
        "x": 759,
        "y": 204
      },
      {
        "x": 1227,
        "y": 204
      }
    ],
    "e4": [
      {
        "x": 749,
        "y": 162
      },
      {
        "x": 759,
        "y": 162
      },
      {
        "x": 759,
        "y": 204
      },
      {
        "x": 1102,
        "y": 204
      },
      {
        "x": 1102,
        "y": 288
      },
      {
        "x": 1227,
        "y": 288
      }
    ],
    "e5": [
      {
        "x": 1507,
        "y": 204
      },
      {
        "x": 1527,
        "y": 204
      }
    ],
    "e6": [
      {
        "x": 1507,
        "y": 204
      },
      {
        "x": 1517,
        "y": 204
      },
      {
        "x": 1517,
        "y": 246
      },
      {
        "x": 1870,
        "y": 246
      },
      {
        "x": 1870,
        "y": 288
      },
      {
        "x": 1985,
        "y": 288
      }
    ],
    "e7": [
      {
        "x": 1507,
        "y": 204
      },
      {
        "x": 1517,
        "y": 204
      },
      {
        "x": 1517,
        "y": 246
      },
      {
        "x": 1870,
        "y": 246
      },
      {
        "x": 1870,
        "y": 204
      },
      {
        "x": 1985,
        "y": 204
      }
    ],
    "e8": [
      {
        "x": 1507,
        "y": 288
      },
      {
        "x": 1985,
        "y": 288
      }
    ],
    "e9": [
      {
        "x": 1507,
        "y": 288
      },
      {
        "x": 1870,
        "y": 288
      },
      {
        "x": 1870,
        "y": 416
      },
      {
        "x": 1961,
        "y": 416
      }
    ],
    "e10": [
      {
        "x": 1807,
        "y": 204
      },
      {
        "x": 1860,
        "y": 204
      },
      {
        "x": 1860,
        "y": 120
      },
      {
        "x": 1985,
        "y": 120
      }
    ]
  },
  "bounds": {
    "width": 2329,
    "height": 488
  }
};
