// Generated by packages/layout/scripts/layout-samples.ts — do not edit.
import type { LaidOutDiagram } from '@stackmap/core';

export const groupedPlatformLayout: LaidOutDiagram = {
  "draft": {
    "kind": "architecture",
    "title": "Platform",
    "subtitle": "Grouped tiers",
    "direction": "RIGHT",
    "groups": [
      {
        "id": "edge-tier",
        "label": "Edge"
      },
      {
        "id": "app-tier",
        "label": "App tier"
      },
      {
        "id": "data-tier",
        "label": "Data tier"
      }
    ],
    "nodes": [
      {
        "id": "web",
        "type": "client",
        "card": {
          "title": "Web app",
          "subtitle": "Next.js",
          "brand": "nextdotjs"
        }
      },
      {
        "id": "gw",
        "type": "gateway",
        "group": "edge-tier",
        "card": {
          "title": "API Gateway",
          "subtitle": "nginx",
          "brand": "nginx"
        }
      },
      {
        "id": "auth",
        "type": "security",
        "group": "edge-tier",
        "card": {
          "title": "Auth",
          "subtitle": "OIDC provider"
        }
      },
      {
        "id": "orders-svc",
        "type": "service",
        "group": "app-tier",
        "card": {
          "title": "orders",
          "subtitle": "Service"
        }
      },
      {
        "id": "billing-svc",
        "type": "service",
        "group": "app-tier",
        "card": {
          "title": "billing",
          "subtitle": "Service"
        }
      },
      {
        "id": "jobs",
        "type": "queue",
        "group": "app-tier",
        "card": {
          "title": "jobs",
          "subtitle": "RabbitMQ",
          "brand": "rabbitmq"
        }
      },
      {
        "id": "db",
        "type": "database",
        "group": "data-tier",
        "card": {
          "title": "postgres",
          "subtitle": "PostgreSQL",
          "brand": "postgresql"
        }
      },
      {
        "id": "kv",
        "type": "cache",
        "group": "data-tier",
        "card": {
          "title": "redis",
          "subtitle": "Redis",
          "brand": "redis"
        }
      },
      {
        "id": "blobs",
        "type": "storage",
        "group": "data-tier",
        "card": {
          "title": "assets",
          "subtitle": "Object storage"
        }
      },
      {
        "id": "stripe",
        "type": "external",
        "card": {
          "title": "Stripe",
          "subtitle": "Payments API",
          "brand": "stripe"
        }
      }
    ],
    "edges": [
      {
        "id": "e1",
        "from": "web",
        "to": "gw",
        "label": "HTTPS"
      },
      {
        "id": "e2",
        "from": "gw",
        "to": "auth"
      },
      {
        "id": "e3",
        "from": "gw",
        "to": "orders-svc"
      },
      {
        "id": "e4",
        "from": "gw",
        "to": "billing-svc"
      },
      {
        "id": "e5",
        "from": "orders-svc",
        "to": "jobs",
        "kind": "async",
        "label": "enqueue"
      },
      {
        "id": "e6",
        "from": "orders-svc",
        "to": "db"
      },
      {
        "id": "e7",
        "from": "orders-svc",
        "to": "kv"
      },
      {
        "id": "e8",
        "from": "billing-svc",
        "to": "db"
      },
      {
        "id": "e9",
        "from": "billing-svc",
        "to": "stripe"
      },
      {
        "id": "e10",
        "from": "jobs",
        "to": "blobs",
        "kind": "async"
      }
    ]
  },
  "nodes": {
    "gw": {
      "x": 911,
      "y": 88,
      "width": 280,
      "height": 64
    },
    "auth": {
      "x": 1271,
      "y": 88,
      "width": 280,
      "height": 64
    },
    "orders-svc": {
      "x": 93,
      "y": 398,
      "width": 280,
      "height": 64
    },
    "billing-svc": {
      "x": 93,
      "y": 482,
      "width": 280,
      "height": 64
    },
    "jobs": {
      "x": 453,
      "y": 398,
      "width": 280,
      "height": 64
    },
    "db": {
      "x": 911,
      "y": 534,
      "width": 280,
      "height": 64
    },
    "kv": {
      "x": 911,
      "y": 450,
      "width": 280,
      "height": 64
    },
    "blobs": {
      "x": 911,
      "y": 366,
      "width": 280,
      "height": 64
    },
    "web": {
      "x": 477,
      "y": 88,
      "width": 280,
      "height": 64
    },
    "stripe": {
      "x": 887,
      "y": 662,
      "width": 280,
      "height": 64
    }
  },
  "groups": {
    "edge-tier": {
      "x": 887,
      "y": 40,
      "width": 688,
      "height": 157
    },
    "app-tier": {
      "x": 69,
      "y": 350,
      "width": 688,
      "height": 220
    },
    "data-tier": {
      "x": 887,
      "y": 318,
      "width": 328,
      "height": 304
    }
  },
  "edges": {
    "e1": [
      {
        "x": 757,
        "y": 120
      },
      {
        "x": 911,
        "y": 120
      }
    ],
    "e2": [
      {
        "x": 1191,
        "y": 120
      },
      {
        "x": 1271,
        "y": 120
      }
    ],
    "e3": [
      {
        "x": 1191,
        "y": 120
      },
      {
        "x": 1201,
        "y": 120
      },
      {
        "x": 1201,
        "y": 172
      },
      {
        "x": 1604,
        "y": 172
      },
      {
        "x": 1604,
        "y": 257
      },
      {
        "x": 40,
        "y": 257
      },
      {
        "x": 40,
        "y": 430
      },
      {
        "x": 93,
        "y": 430
      }
    ],
    "e4": [
      {
        "x": 1191,
        "y": 120
      },
      {
        "x": 1201,
        "y": 120
      },
      {
        "x": 1201,
        "y": 172
      },
      {
        "x": 1604,
        "y": 172
      },
      {
        "x": 1604,
        "y": 257
      },
      {
        "x": 40,
        "y": 257
      },
      {
        "x": 40,
        "y": 514
      },
      {
        "x": 93,
        "y": 514
      }
    ],
    "e5": [
      {
        "x": 373,
        "y": 430
      },
      {
        "x": 453,
        "y": 430
      }
    ],
    "e6": [
      {
        "x": 373,
        "y": 430
      },
      {
        "x": 383,
        "y": 430
      },
      {
        "x": 383,
        "y": 482
      },
      {
        "x": 786,
        "y": 482
      },
      {
        "x": 786,
        "y": 566
      },
      {
        "x": 911,
        "y": 566
      }
    ],
    "e7": [
      {
        "x": 373,
        "y": 430
      },
      {
        "x": 383,
        "y": 430
      },
      {
        "x": 383,
        "y": 482
      },
      {
        "x": 911,
        "y": 482
      }
    ],
    "e8": [
      {
        "x": 373,
        "y": 514
      },
      {
        "x": 786,
        "y": 514
      },
      {
        "x": 786,
        "y": 566
      },
      {
        "x": 911,
        "y": 566
      }
    ],
    "e9": [
      {
        "x": 373,
        "y": 514
      },
      {
        "x": 786,
        "y": 514
      },
      {
        "x": 786,
        "y": 694
      },
      {
        "x": 887,
        "y": 694
      }
    ],
    "e10": [
      {
        "x": 733,
        "y": 430
      },
      {
        "x": 786,
        "y": 430
      },
      {
        "x": 786,
        "y": 398
      },
      {
        "x": 911,
        "y": 398
      }
    ]
  },
  "bounds": {
    "width": 1644,
    "height": 766
  }
};
